FROM alpine:3.20
RUN apk add --no-cache postfix cyrus-sasl cyrus-sasl-login
COPY smtp/main.cf /etc/postfix/main.cf
COPY smtp/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 25
ENTRYPOINT ["/entrypoint.sh"]
