"""End-to-end hash test on a REAL captured PostgreSQL md5 auth handshake.

Fixture ``pgsql/oida_pgsql_md5.pcap`` was generated by capturing a real
``psql`` -> ``postgres:13`` md5 login (see docker/capture/). The account
password is ``S3cretPg1`` for user ``oida``. The extracted line cracks with:

    hashcat -m 11100 '$postgres$oida*427bde42*ca8a6d6e8924b8bfee0ad9a50ae7e0a3' <wordlist>
    -> S3cretPg1   (verified)

This pins the hashcat mode-11100 format end-to-end: signature, ``*`` separators,
salt/hash order, and the stripped ``md5`` prefix.
"""

import pytest

from tests.integration.pcap.conftest import _run_listener_test

pytestmark = [pytest.mark.integration]

EXPECTED = "$postgres$oida*427bde42*ca8a6d6e8924b8bfee0ad9a50ae7e0a3"


def test_pgsql_md5_hash_is_crackable_mode_11100():
    listener, _devices, _result = _run_listener_test(
        "pgsql",
        "PostgreSQLPassiveListener",
        "pgsql",
        "pgsql/oida_pgsql_md5.pcap",
        expect_details=["msg_type"],
    )
    hashes = listener.get_hashcat_hashes()
    assert EXPECTED in hashes, f"expected {EXPECTED!r}, got {hashes}"
    # Shape guard: $postgres$user*salt*hash with a 32-hex digest, no md5 prefix.
    for h in hashes:
        assert h.startswith("$postgres$")
        user, salt, digest = h[len("$postgres$") :].split("*")
        assert user and salt
        assert len(digest) == 32 and all(c in "0123456789abcdef" for c in digest)
        assert not digest.startswith("md5")
