FROM alpine:3.20
RUN apk add --no-cache vsftpd && \
    adduser -D -h /home/ftpuser ftpuser && \
    echo "ftpuser:password" | chpasswd
COPY ftp/vsftpd.conf /etc/vsftpd/vsftpd.conf
EXPOSE 21
CMD ["vsftpd", "/etc/vsftpd/vsftpd.conf"]
