"""
KNX Protocol Data Dictionaries

Contains manufacturer IDs, object types, property IDs, and data type mappings.
Sourced from KNX specification and 2024 OIDA scanner.
"""

# KNX Manufacturer IDs (672 vendors)
VENDORS = {
    1: "Siemens",
    2: "ABB",
    4: "Albrecht Jung",
    5: "Bticino",
    6: "Berker",
    7: "Busch-Jaeger Elektro",
    8: "GIRA Giersiepen",
    9: "Hager Electro",
    10: "Insta GmbH",
    11: "LEGRAND Appareillage électrique",
    12: "Merten",
    14: "ABB SpA-SACE Division",
    22: "Siedle & Söhne",
    24: "Eberle",
    25: "GEWISS",
    27: "Albert Ackermann",
    28: "Schupa GmbH",
    29: "ABB SCHWEIZ",
    30: "Feller",
    31: "Glamox AS",
    32: "DEHN & SÖHNE",
    33: "CRABTREE",
    34: "eVoKNX",
    36: "Paul Hochköpper",
    37: "Altenburger Electronic",
    41: "Grässlin",
    42: "Simon",
    44: "VIMAR",
    45: "Moeller Gebäudeautomation KG",
    46: "Eltako",
    49: "Bosch-Siemens Haushaltsgeräte",
    52: "RITTO GmbH&Co.KG",
    53: "Power Controls",
    55: "ZUMTOBEL",
    57: "Phoenix Contact",
    61: "WAGO Kontakttechnik",
    62: "knXpresso",
    66: "Wieland Electric",
    67: "Hermann Kleinhuis",
    69: "Stiebel Eltron",
    71: "Tehalit",
    72: "Theben AG",
    73: "Wilhelm Rutenbeck",
    75: "Winkhaus",
    76: "Robert Bosch",
    78: "Somfy",
    80: "Woertz",
    81: "Viessmann Werke",
    82: "IMI Hydronic Engineering",
    83: "Joh. Vaillant",
    85: "AMP Deutschland",
    89: "Bosch Thermotechnik GmbH",
    90: "SEF - ECOTEC",
    92: "DORMA GmbH + Co. KG",
    93: "WindowMaster A/S",
    94: "Walther Werke",
    95: "ORAS",
    97: "Dätwyler",
    98: "Electrak",
    99: "Techem",
    100: "Schneider Electric Industries SAS",
    101: "WHD Wilhelm Huber + Söhne",
    102: "Bischoff Elektronik",
    104: "JEPAZ",
    105: "RTS Automation",
    106: "EIBMARKT GmbH",
    107: "WAREMA Renkhoff SE",
    108: "Eelectron",
    109: "Belden Wire & Cable B.V.",
    110: "Becker-Antriebe GmbH",
    111: "J.Stehle+Söhne GmbH",
    112: "AGFEO",
    113: "Zennio",
    114: "TAPKO Technologies",
    115: "HDL",
    116: "Uponor",
    117: "se Lightmanagement AG",
    118: "Arcus-eds",
    119: "Intesis",
    120: "Herholdt Controls srl",
    121: "Niko-Zublin",
    122: "Durable Technologies",
    123: "Innoteam",
    124: "ise GmbH",
    125: "TEAM FOR TRONICS",
    126: "CIAT",
    127: "Remeha BV",
    128: "ESYLUX",
    129: "BASALTE",
    130: "Vestamatic",
    131: "MDT technologies",
    132: "Warendorfer Küchen GmbH",
    133: "Video-Star",
    134: "Sitek",
    135: "CONTROLtronic",
    136: "function Technology",
    137: "AMX",
    138: "ELDAT",
    139: "Panasonic",
    140: "Pulse Technologies",
    141: "Crestron",
    142: "STEINEL professional",
    143: "BILTON LED Lighting",
    144: "denro AG",
    145: "GePro",
    146: "preussen automation",
    147: "Zoppas Industries",
    148: "MACTECH",
    149: "TECHNO-TREND",
    150: "FS Cables",
    151: "Delta Dore",
    152: "Eissound",
    153: "Cisco",
    154: "Dinuy",
    155: "iKNiX",
    156: "Rademacher Geräte-Elektronik GmbH",
    157: "EGi Electroacustica General Iberica",
    158: "Bes – Ingenium",
    159: "ElabNET",
    160: "Blumotix",
    161: "Hunter Douglas",
    162: "APRICUM",
    163: "TIANSU Automation",
    164: "Bubendorff",
    165: "MBS GmbH",
    166: "Enertex Bayern GmbH",
    167: "BMS",
    168: "Sinapsi",
    169: "Embedded Systems SIA",
    170: "KNX1",
    171: "Tokka",
    172: "NanoSense",
    173: "PEAR Automation GmbH",
    174: "DGA",
    175: "Lutron",
    176: "AIRZONE – ALTRA",
    177: "Lithoss Design Switches",
    178: "3ATEL",
    179: "Philips Controls",
    180: "VELUX A/S",
    181: "LOYTEC",
    182: "Ekinex S.p.A.",
    183: "SIRLAN Technologies",
    184: "ProKNX SAS",
    185: "IT GmbH",
    186: "RENSON",
    187: "HEP Group",
    188: "Balmart",
    189: "GFS GmbH",
    190: "Schenker Storen AG",
    191: "Algodue Elettronica S.r.L.",
    192: "ABB France",
    193: "maintronic",
    194: "Vantage",
    195: "Foresis",
    196: "Research & Production Association SEM",
    197: "Weinzierl Engineering GmbH",
    198: "Möhlenhoff Wärmetechnik GmbH",
    199: "PKC-GROUP Oyj",
    200: "B.E.G.",
    201: "Elsner Elektronik GmbH",
    202: "Siemens Building Technologies (HK/China) Ltd.",
    204: "Eutrac",
    205: "Gustav Hensel GmbH & Co. KG",
    206: "GARO AB",
    207: "Waldmann Lichttechnik",
    208: "SCHÜCO",
    209: "EMU",
    210: "JNet Systems AG",
    211: "Total Solution GmbH",
    214: "O.Y.L. Electronics",
    215: "Galax System",
    216: "Disch",
    217: "Aucoteam",
    218: "Luxmate Controls",
    219: "Danfoss",
    220: "AST GmbH",
    222: "WILA Leuchten",
    223: "b+b Automations- und Steuerungstechnik",
    225: "Lingg & Janke",
    227: "Sauter",
    228: "SIMU",
    232: "Theben HTS AG",
    233: "Amann GmbH",
    234: "BERG Energiekontrollsysteme GmbH",
    235: "Hüppe Form Sonnenschutzsysteme GmbH",
    237: "Oventrop KG",
    238: "Griesser AG",
    239: "IPAS GmbH",
    240: "elero GmbH",
    241: "Ardan Production and Industrial Controls Ltd.",
    242: "Metec Meßtechnik GmbH",
    244: "ELKA-Elektronik GmbH",
    245: "ELEKTROANLAGEN D. NAGEL",
    246: "Tridonic Bauelemente GmbH",
    248: "Stengler Gesellschaft",
    249: "Schneider Electric (MG)",
    250: "KNX Association",
    251: "VIVO",
    252: "Hugo Müller GmbH & Co KG",
    253: "Siemens HVAC",
    254: "APT",
    256: "HighDom",
    257: "Top Services",
    258: "ambiHome",
    259: "DATEC electronic AG",
    260: "ABUS Security-Center",
    261: "Lite-Puter",
    262: "Tantron Electronic",
    263: "Interra",
    264: "DKX Tech",
    265: "Viatron",
    266: "Nautibus",
    267: "ON Semiconductor",
    268: "Longchuang",
    269: "Air-On AG",
    270: "ib-company GmbH",
    271: "Sation Factory",
    272: "Agentilo GmbH",
    273: "Makel Elektrik",
    274: "Helios Ventilatoren",
    275: "Otto Solutions Pte Ltd",
    276: "Airmaster",
    277: "Vallox GmbH",
    278: "Dalitek",
    279: "ASIN",
    280: "Bridges Intelligence Technology Inc.",
    281: "ARBONIA",
    282: "KERMI",
    283: "PROLUX",
    284: "ClicHome",
    285: "COMMAX",
    286: "EAE",
    287: "Tense",
    288: "Seyoung Electronics",
    289: "Lifedomus",
    290: "EUROtronic Technology GmbH",
    291: "tci",
    292: "Rishun Electronic",
    293: "Zipato",
    294: "cm-security GmbH & Co KG",
    295: "Qing Cables",
    296: "LABIO",
    297: "Coster Tecnologie Elettroniche S.p.A.",
    298: "E.G.E",
    299: "NETxAutomation",
    300: "tecalor",
    301: "Urmet Electronics (Huizhou) Ltd.",
    302: "Peiying Building Control",
    303: "BPT S.p.A. a Socio Unico",
    304: "Kanontec - KanonBUS",
    305: "ISER Tech",
    306: "Fineline",
    307: "CP Electronics Ltd",
    308: "Niko-Servodan A/S",
    309: "Simon",
    310: "GM modular pvt. Ltd.",
    311: "FU CHENG Intelligence",
    312: "NexKon",
    313: "FEEL s.r.l",
    315: "Shenzhen Fanhai Sanjiang Electronics Co., Ltd.",
    316: "Jiuzhou Greeble",
    317: "Aumüller Aumatic GmbH",
    318: "Etman Electric",
    319: "Black Nova",
    320: "ZidaTech AG",
    321: "IDGS bvba",
    322: "dakanimo",
    323: "Trebor Automation AB",
    324: "Satel sp. z o.o.",
    325: "Russound, Inc.",
    326: "Midea Heating & Ventilating Equipment CO LTD",
    327: "Consorzio Terranuova",
    328: "Wolf Heiztechnik GmbH",
    329: "SONTEC",
    330: "Belcom Cables Ltd.",
    331: "Guangzhou SeaWin Electrical Technologies Co., Ltd.",
    332: "Acrel",
    333: "KWC Aquarotter GmbH",
    334: "Orion Systems",
    335: "Schrack Technik GmbH",
    336: "INSPRID",
    337: "Sunricher",
    338: "Menred automation system(shanghai) Co.,Ltd.",
    339: "Aurex",
    340: "Josef Barthelme GmbH & Co. KG",
    341: "Architecture Numerique",
    342: "UP GROUP",
    343: "Teknos-Avinno",
    344: "Ningbo Dooya Mechanic & Electronic Technology",
    345: "Thermokon Sensortechnik GmbH",
    346: "BELIMO Automation AG",
    347: "Zehnder Group International AG",
    348: "sks Kinkel Elektronik",
    349: "ECE Wurmitzer GmbH",
    350: "LARS",
    351: "URC",
    352: "LightControl",
    353: "ShenZhen YM",
    354: "MEAN WELL Enterprises Co. Ltd.",
    355: "OSix",
    356: "AYPRO Technology",
    357: "Hefei Ecolite Software",
    358: "Enno",
    359: "OHOSURE",
    360: "Garefowl",
    361: "GEZE",
    362: "LG Electronics Inc.",
    363: "SMC interiors",
    365: "SCS Cable",
    366: "Hoval",
    367: "CANST",
    368: "HangZhou Berlin",
    369: "EVN-Lichttechnik",
    370: "rutec",
    371: "Finder",
    372: "Fujitsu General Limited",
    373: "ZF Friedrichshafen AG",
    374: "Crealed",
    375: "Miles Magic Automation Private Limited",
    376: "E+",
    377: "Italcond",
    378: "SATION",
    379: "NewBest",
    380: "GDS DIGITAL SYSTEMS",
    381: "Iddero",
    382: "MBNLED",
    383: "VITRUM",
    384: "ekey biometric systems GmbH",
    385: "AMC",
    386: "TRILUX GmbH & Co. KG",
    387: "WExcedo",
    388: "VEMER SPA",
    389: "Alexander Bürkle GmbH & Co KG",
    390: "Citron",
    391: "Shenzhen HeGuang",
    393: "TRANE B.V.B.A",
    394: "CAREL",
    395: "Prolite Controls",
    396: "BOSMER",
    397: "EUCHIPS",
    398: "connect (Thinka connect)",
    399: "PEAKnx a DOGAWIST company",
    400: "ACEMATIC",
    401: "ELAUSYS",
    402: "ITK Engineering AG",
    403: "INTEGRA METERING AG",
    404: "FMS Hospitality Pte Ltd",
    405: "Nuvo",
    406: "Lux GmbH",
    407: "Brumberg Leuchten",
    408: "Lime",
    409: "Great Empire International Group Co., Ltd.",
    410: "Kavoshpishro Asia",
    411: "V2 SpA",
    412: "Johnson Controls",
    413: "Arkud",
    414: "Iridium Ltd.",
    415: "bsmart",
    416: "BAB TECHNOLOGIE GmbH",
    417: "NICE Spa",
    418: "Redfish Group Pty Ltd",
    419: "SABIANA spa",
    420: "Ubee Interactive Europe",
    421: "Rexel",
    422: "Ges Teknik A.S.",
    423: "Ave S.p.A.",
    424: "Zhuhai Ltech Technology Co., Ltd.",
    425: "ARCOM",
    426: "VIA Technologies, Inc.",
    427: "FEELSMART.",
    428: "SUPCON",
    429: "MANIC",
    430: "TDE GmbH",
    431: "Nanjing Shufan Information technology Co.,Ltd.",
    432: "EWTech",
    433: "Kluger Automation GmbH",
    434: "JoongAng Control",
    435: "GreenControls Technology Sdn. Bhd.",
    436: "IME S.p.a.",
    437: "SiChuan HaoDing",
    438: "Mindjaga Ltd.",
    439: "RuiLi Smart Control",
    440: "CODESYS GmbH",
    441: "Moorgen Deutschland GmbH",
    442: "CULLMANN TECH",
    443: "eyrise B.V",
    444: "ABEGO",
    445: "myGEKKO",
    446: "Ergo3 Sarl",
    447: "STmicroelectronics International N.V.",
    448: "cjc systems",
    449: "Sudoku",
    451: "AZ e-lite Pte Ltd",
    452: "Arlight",
    453: "Grünbeck Wasseraufbereitung GmbH",
    454: "Module Electronic",
    455: "KOPLAT",
    456: "Guangzhou Letour Life Technology Co., Ltd",
    457: "ILEVIA",
    458: "LN SYSTEMTEQ",
    459: "Hisense SmartHome",
    460: "Flink Automation System",
    461: "xxter bv",
    462: "lynxus technology",
    463: "ROBOT S.A.",
    464: "Shenzhen Atte Smart Life Co.,Ltd.",
    465: "Noblesse",
    466: "Advanced Devices",
    467: "Atrina Building Automation Co. Ltd",
    468: "Guangdong Daming Laffey electric Co., Ltd.",
    469: "Westerstrand Urfabrik AB",
    470: "Control4 Corporate",
    471: "Ontrol",
    472: "Starnet",
    473: "BETA CAVI",
    474: "EaseMore",
    475: "Vivaldi srl",
    476: "Gree Electric Appliances,Inc. of Zhuhai",
    477: "HWISCON",
    478: "Shanghai ELECON Intelligent Technology Co., Ltd.",
    479: "Kampmann",
    480: "Impolux GmbH / LEDIMAX",
    481: "Evaux",
    482: "Webro Cables & Connectors Limited",
    483: "Shanghai E-tech Solution",
    484: "Guangzhou HOKO Electric Co.,Ltd.",
    485: "LAMMIN HIGH TECH CO.,LTD",
    486: "Shenzhen Merrytek Technology Co., Ltd",
    487: "I-Luxus",
    488: "Elmos Semiconductor AG",
    489: "EmCom Technology Inc",
    490: "project innovations GmbH",
    491: "Itc",
    492: "ABB LV Installation Materials Company Ltd, Beijing",
    493: "Maico",
    495: "ELAN SRL",
    496: "MinhHa Technology co.,Ltd",
    497: "Zhejiang Tianjie Industrial CORP.",
    498: "iAutomation Pty Limited",
    499: "Extron",
    500: "Freedompro",
    501: "1Home",
    502: "EOS Saunatechnik GmbH",
    503: "KUSATEK GmbH",
    504: "EisBär Scada",
    505: "AUTOMATISMI BENINCA S.P.A.",
    506: "Blendom",
    507: "Madel Air Technical diffusion",
    508: "NIKO",
    509: "Bosch Rexroth AG",
    512: "C&M Products",
    513: "Hörmann KG Verkaufsgesellschaft",
    514: "Shanghai Rajayasa co.,LTD",
    515: "SUZUKI",
    516: "Silent Gliss International Ltd.",
    517: "BEE Controls (ADGSC Group)",
    518: "xDTecGmbH",
    519: "OSRAM",
    520: "Lebenor",
    521: "automaneng",
    522: "Honeywell Automation Solution control(China)",
    523: "Hangzhou binthen Intelligence Technology Co.,Ltd",
    524: "ETA Heiztechnik",
    525: "DIVUS GmbH",
    526: "Nanjing Taijiesai Intelligent Technology Co. Ltd.",
    527: "Lunatone",
    528: "ZHEJIANG SCTECH BUILDING INTELLIGENT",
    529: "Foshan Qite Technology Co., Ltd.",
    530: "NOKE",
    531: "LANDCOM",
    532: "Stork AS",
    533: "Hangzhou Shendu Technology Co., Ltd.",
    534: "CoolAutomation",
    535: "Aprstern",
    536: "sonnen",
    537: "DNAKE",
    538: "Neuberger Gebäudeautomation GmbH",
    539: "Stiliger",
    540: "Berghof Automation GmbH",
    541: "Total Automation and controls GmbH",
    542: "dovit",
    543: "Instalighting GmbH",
    544: "UNI-TEC",
    545: "CasaTunes",
    546: "EMT",
    547: "Senfficient",
    548: "Aurolite electrical panyu guangzhou limited",
    549: "ABB Xiamen Smart Technology Co., Ltd.",
    550: "Samson Electric Wire",
    551: "T-Touching",
    552: "Core Smart Home",
    553: "GreenConnect Solutions SA",
    554: "ELETTRONICA CONDUTTORI",
    555: "MKFC",
    556: "Automation+",
    557: "blue and red",
    558: "frogblue",
    559: "SAVESOR",
    560: "App Tech",
    561: "sensortec AG",
    562: "nysa technology & solutions",
    563: "FARADITE",
    564: "Optimus",
    565: "KTS s.r.l.",
    566: "Ramcro SPA",
    567: "Wuhan WiseCreate Universe Technology Co., Ltd",
    568: "BEMI Smart Home Ltd",
    569: "Ardomus",
    570: "ChangXing",
    571: "E-Controls",
    572: "AIB Technology",
    573: "NVC",
    574: "Kbox",
    575: "CNS",
    576: "Tyba",
    577: "Atrel",
    578: "Simon Electric (China) Co., LTD",
    579: "Kordz Group",
    580: "ND Electric",
    581: "Controlium",
    582: "FAMO GmbH & Co. KG",
    583: "CDN Smart",
    584: "Heston",
    585: "ESLA CONEXIONES S.L.",
    586: "Weishaupt",
    587: "ASTRUM TECHNOLOGY",
    588: "WUERTH ELEKTRONIK STELVIO KONTEK S.p.A.",
    589: "NANOTECO corporation",
    590: "Nietian",
    591: "Sumsir",
    592: "ORBIS TECNOLOGIA ELECTRICA SA",
    593: "Nanjing Zhongyi IoT Technology Co., Ltd.",
    594: "Anlips",
    595: "GUANGDONG PAK CORPORATION CO., LTD",
    596: "BVK Technology",
    597: "Solomio srl",
    598: "Domotica Labs",
    599: "NVC International",
    600: "BA",
    601: "Iris Ceramica Group",
    602: "Wireeo",
    603: "nvclighting",
    604: "Jinan Tian Da Sheng Information Technology Co.",
    605: "Armiti trading",
    606: "ELEK",
    607: "Accordia sa",
    608: "OURICAN",
    609: "INLIWOSE",
    610: "Bosch (Shanghai) Smart Life Technology Ltd.",
    611: "SHK KNX",
    612: "Ampio",
    613: "Mingxing Wisdom",
    614: "ALTEN SW GmbH",
    615: "V.Y.C.srl",
    616: "TERMINUS GROUP",
    617: "Wonderful City Technology",
    618: "QbicTechnology",
    619: "Embedded Automation Equipment (Shanghai) Limited",
    620: "onework",
    621: "PL LINK",
    622: "Fasel GmbH Elektronik",
    623: "GoldenHome Smart",
    624: "Goldmedal",
    625: "Can'nX",
    627: "EGI - Earth Goodness",
    628: "Viega GmbH & Co. KG",
    629: "Fredon Digital Buildings",
    630: "Helukabel (Thailand) Co.,Ltd.",
    631: "ACE Technology",
    632: "MEX Electric Technology (Shanghai) Co., Ltd",
    633: "SUMAMO",
    634: "SVIT",
    635: "tecget",
    636: "Xeropoint",
    637: "Honeywell Building Technologies",
    638: "ComfortClick",
    639: "DORBAS ELECTRIC",
    640: "REMKO GmbH & Co. KG",
    641: "Shenzhen Congxun Intelligent Technology Co., LTD",
    642: "ANDAS",
    643: "Hefei Chuang Yue Intelligent Technology Co.,LTD",
    644: "Larfe",
    645: "Dongguan Muhcci Electrical",
    646: "STEC",
    647: "ARIGO Software GmbH",
    648: "Feishelec",
    649: "GORDIC",
    650: "Delta Electronics",
    651: "Shanghai Lewin Intelligent Technology Co.,Ltd.",
    652: "KG-POWER",
    653: "Zhejiang Moorgen Group Co.,Ltd",
    654: "Guangdong Kanway",
    656: "RAMIREZ Engineering GmbH",
    657: "Zhongshan Taiyang IMP&EXP. CO LTD",
    658: "Vihan electric pvt ltd",
    659: "Splendid Minds GmbH",
    660: "Estada",
    661: "zhongyunxinzhikonggujituanyouxiangongsi",
    662: "Stuhl Regelsysteme GmbH",
    663: "Shenzhen Gluck Technology Co., LTD",
    664: "Gaimex",
    665: "B3 International S.R.L",
    666: "MM Electro",
    667: "CASCODA",
    668: "Xiamen Intretech Inc.",
    669: "KiloElec Technology",
    670: "Inyx",
    671: "Smart Building Services GmbH",
    672: "BSS GmbH",
}

# KNX Interface Object Types
OBJECT_TYPES = {
    0: "Device Object",
    1: "Address Table Object",
    2: "Association Table Object",
    3: "Application Program Object",
    4: "Application Program 2 Object",
    5: "KNX-Object Associationtable Object",
    6: "Router Object",
    7: "LTE Address Routing Table Object",
    8: "cEMI Server Object",
    9: "Group Object Table Object",
    10: "Polling Master",
    11: "KNXnet/IP Parameter Object",
    13: "File Server Object",
    17: "Security Object",
    19: "RF Medium Object",
    409: "Indoor Brightness Sensor",
    410: "Indoor Luminance Sensor",
    417: "Light Switching Actuator Basic",
    418: "Dimming Actuator Basic",
    420: "Dimming Sensor Basic",
    421: "Switching Sensor Basic",
    800: "Sunblind Actuator Basic",
    801: "Sunblind Sensor Basic",
}

# Property IDs by Object Type
OBJECT_PROP_TYPES = {
    0: {  # Device Object
        51: "ROUTING_COUNT",
        52: "MAX_RETRY_COUNT",
        53: "ERROR_FLAGS",
        54: "PROGMODE",
        55: "PRODUCT_ID",
        56: "MAX_APDULENGTH",
        57: "SUBNET_ADDR",
        58: "DEVICE_ADDR",
        59: "PB_CONFIG",
        60: "ADDR_REPORT",
        61: "ADDR_CHECK",
        62: "OBJECT_VALUE",
        63: "OBJECTLINK",
        64: "APPLICATION",
        65: "PARAMETER",
        66: "OBJECTADDRESS",
        67: "PSU_TYPE",
        68: "PSU_STATUS",
        69: "PSU_ENABLE",
        70: "DOMAIN_ADDRESS",
        71: "IO_LIST",
        72: "MGT_DESCRIPTOR_01",
        73: "PL110_PARAM",
        74: "RF_REPEAT_COUNTER",
        75: "RECEIVE_BLOCK_TABLE",
        76: "RANDOM_PAUSE_TABLE",
        77: "RECEIVE_BLOCK_NR",
        78: "HARDWARE_TYPE",
        79: "RETRANSMITTER_NUMBER",
        80: "SERIAL_NR_TABLE",
        81: "BIBATMASTER_ADDRESS",
        82: "RF_DOMAIN_ADDRESS",
        83: "DEVICE_DESCRIPTOR",
        84: "METERING_FILTER_TABLE",
        85: "GROUP_TELEGR_RATE_LIMIT_TIME_BASE",
        86: "GROUP_TELEGR_RATE_LIMIT_NO_OF_TELEGR",
        87: "MAX_BASIC_PERIOD",
        88: "RANDOM_NUMBER",
        89: "FEATURES_SUPPORTED",
        90: "DEVICE_DESCRIPTOR_2",
        91: "APPLICATION_ID",
        92: "APP_MANUFACTURER_ID",
        93: "APP_VERSION_NUMBER",
        94: "DOWNLOAD_COUNTER",
        95: "MULTICAST_DOMAIN_ADDRESS",
        96: "FIRMWARE_REVISION_1",
        97: "FIRMWARE_REVISION_2",
        98: "HW_PRODUCT_CODE",
        99: "MEDIUM_TYPE_CONFIG",
        100: "MEDIUM_STATUS",
        101: "CHANNEL_01_PARAM",
        102: "CHANNEL_02_PARAM",
        103: "CHANNEL_03_PARAM",
        104: "CHANNEL_04_PARAM",
        105: "CHANNEL_05_PARAM",
        106: "CHANNEL_06_PARAM",
        107: "CHANNEL_07_PARAM",
        108: "CHANNEL_08_PARAM",
        109: "CHANNEL_09_PARAM",
        110: "CHANNEL_10_PARAM",
        111: "CHANNEL_11_PARAM",
        112: "CHANNEL_12_PARAM",
        113: "CHANNEL_13_PARAM",
        114: "CHANNEL_14_PARAM",
        115: "CHANNEL_15_PARAM",
        116: "CHANNEL_16_PARAM",
        117: "CHANNEL_17_PARAM",
        118: "CHANNEL_18_PARAM",
        119: "CHANNEL_19_PARAM",
        120: "CHANNEL_20_PARAM",
        121: "CHANNEL_21_PARAM",
        122: "CHANNEL_22_PARAM",
        123: "CHANNEL_23_PARAM",
        124: "CHANNEL_24_PARAM",
        125: "CHANNEL_25_PARAM",
        126: "CHANNEL_26_PARAM",
        127: "CHANNEL_27_PARAM",
        128: "CHANNEL_28_PARAM",
        129: "CHANNEL_29_PARAM",
        130: "CHANNEL_30_PARAM",
        131: "CHANNEL_31_PARAM",
        132: "CHANNEL_32_PARAM",
    },
    1: {  # Address Table Object
        51: "EXT_FRAMEFORMAT",
        52: "ADDRTAB1",
        53: "GROUP_RESPONSER_TABLE",
    },
    2: {  # Association Table Object
        52: "TABLE",
    },
    3: {  # Application Program Object
        51: "PARAM_REFERENCE",
        52: "OPERATION_MODE",
    },
    4: {  # Interface Program Object
        51: "PARAM_REFERENCE",
    },
    5: {  # KNX Object Association Table Object
        51: "TABLE",
    },
    6: {  # Router Object
        51: "MEDIUM_STATUS",
        52: "MAIN_LCCONFIG",
        53: "SUB_LCCONFIG",
        54: "MAIN_LCGRPCONFIG",
        55: "SUB_LCGRPCONFIG",
        56: "ROUTETABLE_CONTROL",
        57: "COUPL_SERV_CONTROL",
        58: "MAX_APDULENGTH_ROUTING",
        59: "COUPLER_TYPE",
        61: "HOP_COUNT",
        63: "MEDIUM",
        67: "FILTER_TABLE_USE",
        68: "DA_FILTER_TABLE",
        69: "TEMP_DA_FILTER_CONTROL",
        79: "RF_MULTI_UNICAST_CONTROL",
        80: "PTP_CONFIG",
        81: "SECURITY_PROXY_GRP_KEY_TABLE",
        82: "BC_CONFIG",
        83: "PTP_ROUTING_TEMP",
        84: "BC_ROUTING_TEMP",
        112: "RF_SBC_CONTROL",
        114: "RF_MULTI_BROADCAST_CONTROL",
        120: "IP_SBC_CONTROL",
        201: "MAIN_LCGRPCONFIG_HIGH",
        202: "SUB_LCGRPCONFIG_HIGH",
        203: "ENX_SYSTEMBC",
        206: "ENX_SEND_ALAWAYS_ACK",
        208: "ENX_LOCK_PROGKNX",
        209: "ENX_LEGACY_ROUTING",
    },
    7: {  # LTE Address Routing Table Object
        51: "LTE_ROUTESELECT",
        52: "LTE_ROUTETABLE",
    },
    8: {  # cEMI Server Object
        51: "MEDIUM_TYPE",
        52: "COMM_MODE",
        53: "MEDIUM_AVAILABILITY",
        54: "ADD_INFO_TYPES",
        55: "TIME_BASE",
        56: "MAX_APDULENGTH",
        57: "CLIENT_SNA",
        58: "CLIENT_DEVICE_ADDRESS",
        59: "BIBAT_NEXTBLOCK",
        60: "RF_BIDIR_TIMEOUT",
        61: "RF_MODE_SUPPORT",
        62: "RF_FILTERING_MODE_SELECT",
        63: "RF_FILTERING_MODE_SUPPORT",
        64: "COMM_MODES_SUPPORTED",
        65: "FILTERING_MODE_SUPPORT",
        66: "FILTERING_MODE_SELECT",
        68: "MAX_INTERFACE_APDU_LENGTH",
        69: "MAX_LOCAL_APDU_LENGTH",
        70: "RF_MULTI_SENDING_ACK",
        72: "RF_MULTI_ADDINFO_SELECT",
        75: "RF_TYPES_SUPPORTED",
        90: "SLOW_LE_DEST_ADDR_CHECK",
        96: "RF_MULTI_LL_TIMEOUT_VALUES",
    },
    9: {  # Group Object Table Object
        51: "GRPOBJTABLE",
        52: "EXT_GRPOBJREFERENCE",
        66: "GO_DIAGNOSTICS",
    },
    10: {  # Polling Master
        51: "POLLING_STATE",
        52: "POLLING_SLAVE_ADDR",
        53: "POLL_CYCLE",
    },
    11: {  # KNXnet/IP Parameter Object
        51: "PROJECT_INSTALLATION_ID",
        52: "KNX_INDIVIDUAL_ADDRESS",
        53: "ADDITIONAL_INDIVIDUAL_ADDRESSES",
        54: "CURRENT_IP_ASSIGNMENT_METHOD",
        55: "IP_ASSIGNMENT_METHOD",
        56: "IP_CAPABILITIES",
        57: "CURRENT_IP_ADDRESS",
        58: "CURRENT_SUBNET_MASK",
        59: "CURRENT_DEFAULT_GATEWAY",
        60: "IP_ADDRESS",
        61: "SUBNET_MASK",
        62: "DEFAULT_GATEWAY",
        63: "DHCP_BOOTP_SERVER",
        64: "MAC_ADDRESS",
        65: "SYSTEM_SETUP_MULTICAST_ADDRESS",
        66: "ROUTING_MULTICAST_ADDRESS",
        67: "TTL",
        68: "KNXNETIP_DEVICE_CAPABILITIES",
        69: "KNXNETIP_DEVICE_STATE",
        70: "KNXNETIP_ROUTING_CAPABILITIES",
        71: "PRIORITY_FIFO_ENABLED",
        72: "QUEUE_OVERFLOW_TO_IP",
        73: "QUEUE_OVERFLOW_TO_KNX",
        74: "MSG_TRANSMIT_TO_IP",
        75: "MSG_TRANSMIT_TO_KNX",
        76: "FRIENDLY_NAME",
        77: "ROUTING_BACKBONE_TIMEOUT",
        78: "ROUTING_BUSY_WAIT_TIME",
        79: "TUNNELING_ADDRESSES",
        80: "FDSK",
        81: "PROGRAMMING_MODE",
        82: "PROTOCOL_VERSION",
        83: "PRIMARY_DOMAIN_ADDRESS",
        84: "INTERFACE_INDIVIDUAL_ADDRESS",
        85: "INTERFACE_OBJECT_TYPE",
        86: "IPV6_CAPABLE",
        87: "IPV6_ADDRESSES",
        88: "ROUTING_BACKBONE_KEY",
        89: "DEFAULT_DEVICE_AUTHENTICATION_CODE",
        90: "DEFAULT_USER_PASSWORD",
        91: "BACKBONE_KEY",
        92: "DEVICE_AUTHENTICATION_CODE",
        93: "PASSWORD_HASHES",
        94: "SECURED_SERVICE_FAMILIES",
        95: "MULTICAST_LATENCY_TOLERANCE",
        96: "SYNC_LATENCY_FRACTION",
        97: "TUNNELING_USERS",
        204: "ENX_TUNNELING_REQUEST_TIMEOUT",
        205: "ENX_BASICCRI_TUNNELING_PREFERRED_IP",
        207: "ENX_TUNNELING_UDP",
    },
    12: {  # Object Type 12
        51: "AR_TYPE_REPORT",
    },
    13: {  # File Server Object
        51: "FILE_HANDLE",
        52: "FILE_LENGTH",
        53: "FILE_ACCESS",
        54: "FILE_MEDIA_TYPE",
    },
    17: {  # Security Object
        51: "SECURITY_MODE",
        52: "P2P_KEY_TABLE",
        53: "GRP_KEY_TABLE",
        54: "SECURITY_INDIVIDUAL_ADDRESS_TABLE",
        55: "SECURITY_FAILURES_LOG",
        56: "TOOL_KEY",
        57: "SECURITY_REPORT",
        58: "SECURITY_REPORT_CONTROL",
        59: "SEQUENCE_NUMBER_SENDING",
        60: "ZONE_KEY_TABLE",
        61: "GO_SECURITY_FLAGS",
        62: "ROLE_TABLE",
    },
    19: {  # RF Medium Object
        51: "RF_MULTI_TYPE",
        52: "RF_MULTI_PHYSICAL_FEATURES",
        53: "RF_MULTI_CALL_CHANNEL",
        54: "RF_MULTI_OBJECT_LINK",
        55: "RF_MULTI_EXT_GA_REPEATED",
        56: "RF_DOMAIN_ADDRESS",
        57: "RF_RETRANSMITTER",
        58: "RF_FILTERING_MODE_SUPPORT",
        59: "RF_FILTERING_MODE_SELECT",
        60: "RF_BIDIR_TIMEOUT",
        61: "RF_DIAG_SA_FILTER_TABLE",
        62: "RF_DIAG_QUALITY_TABLE",
        63: "RF_DIAG_PROBE",
        70: "TRANSMISSION_MODE",
        71: "RECEPTION_MODE",
        76: "GRP_TX_MULTI_INFO_TABLE",
        77: "GRP_RX_MULTI_INFO_TABLE",
        78: "RF_MULTI_MEDIA_COUPLER_TYPE",
        82: "GRP_TP_RF_MULTICAST_TABLE",
        83: "GRP_RF_TP_MULTICAST_TABLE",
        88: "RF_MULTI_RX_READY",
        89: "LAST_TRANSMISSION_MODE",
        90: "SLOW_LE_DISABLE_DEST_ADDR_CHECK",
        92: "RF_MULTI_RF_CHANNEL_F3_SETTINGS",
        93: "READY_SLOW_RESENDER_TABLE",
        94: "GRP_READY_SLOW_RESENDER_TABLE",
        96: "RF_MULTI_LL_TIMEOUT_VALUES",
    },
    50001: {  # ENX Object
        209: "ENX_BLOCKFILTER",
        211: "ENX_TELEGRAMMRATE_LIMIT",
    },
    # Application Object Types
    409: {  # Indoor Brightness Sensor
        110: "CHANGE_OF_VALUE",
        111: "REPETITION_TIME",
    },
    410: {  # Indoor Luminance Sensor
        110: "CHANGE_OF_VALUE",
        111: "REPETITION_TIME",
    },
    417: {  # Light Switching Actuator Basic
        101: "ON_DELAY",
        102: "OFF_DELAY",
        103: "TIMED_ON_DURATION",
        104: "PREWARNING_DURATION",
        105: "TRANSMISSION_CYCLE_TIME",
        106: "BUS_POWER_UP_MESSAGE_DELAY",
        107: "BEHAVIOUR_AT_LOCKING",
        108: "BEHAVIOUR_AT_UNLOCKING",
        109: "BEHAVIOUR_BUS_POWER_UP",
        110: "BEHAVIOUR_BUS_POWER_DOWN",
        111: "INVERT_OUTPUT_STATE",
        112: "TIMED_ON_RETRIGGER_FUNCTION",
        113: "MANUAL_OFF_ENABLE",
        114: "INVERT_LOCK_DEVICE",
        115: "LOCK_STATE",
        116: "UNLOCK_STATE",
        117: "STATE_FOR_SCENE_NUMBER",
        118: "STORAGE_FUNCTION_FOR_SCENE",
        119: "BUS_POWER_UP_STATE",
        120: "BEHAVIOUR_BUS_POWER_UP_STATE",
    },
    418: {  # Dimming Actuator Basic
        101: "ON_DELAY",
        102: "OFF_DELAY",
        103: "SWITCH_OFF_BRIGHTNESS_DELAY_TIME",
        104: "TIMED_ON_DURATION",
        105: "PREWARNING_DURATION",
        106: "TRANSMISSION_CYCLE_TIME",
        107: "BUS_POWER_UP_MESSAGE_DELAY",
        108: "DIMMING_SPEED",
        109: "DIMMING_STEP_TIME",
        110: "DIMMING_SPEED_FOR_SWITCH_ON_SET_VALUE",
        111: "DIMMING_SPEED_FOR_SWITCH_OFF",
        112: "DIMMING_STEP_TIME_FOR_SWITCH_ON_SET_VALUE",
        113: "DIMMING_STEP_TIME_FOR_SWITCH_OFF",
        114: "SWITCH_OFF_BRIGHTNESS",
        115: "MINIMUM_SET_VALUE",
        116: "MAXIMUM_SET_VALUE",
        117: "SWITCH_ON_SET_VALUE",
        118: "DIMM_MODE_SELECTION",
        119: "RELATIV_OFF_ENABLE",
        120: "MEMORY_FUNCTION",
        121: "TIMED_ON_RETRIGGER_FUNCTION",
        122: "MANUAL_OFF_ENABLE",
        123: "INVERT_LOCK_DEVICE",
        124: "BEHAVIOUR_AT_LOCKING",
        125: "BEHAVIOUR_AT_UNLOCKING",
        126: "LOCK_SETVALUE",
        127: "UNLOCK_SETVALUE",
        128: "BRIGHTNESS_FOR_SCENE",
        129: "STORAGE_FUNCTION_FOR_SCENE",
        130: "DELTA_DIMMING_VALUE",
        131: "BEHAVIOUR_BUS_POWER_UP",
        132: "BEHAVIOUR_BUS_POWER_UP_SET_VALUE",
        133: "BEHAVIOUR_BUS_POWER_DOWN",
        134: "BUS_POWER_DOWN_SET_VALUE",
    },
    420: {  # Dimming Sensor Basic
        51: "ON_OFF_ACTION",
        52: "ENABLE_TOGGLE_MODE",
        53: "ABSOLUTE_SETVALUE",
    },
    421: {  # Switching Sensor Basic
        51: "ON_OFF_ACTION",
        52: "ENABLE_TOGGLE_MODE",
    },
    800: {  # Sunblind Actuator Basic
        51: "REVERSION_PAUSE_TIME",
        52: "MOVE_UP_DOWN_TIME",
        53: "SLAT_STEP_TIME",
        54: "MOVE_PRESET_POSITION_TIME",
        55: "MOVE_TO_PRESET_POSITION_PERCENT",
        57: "MOVE_TO_PRESET_POSITION_LENGTH",
        58: "PRESET_SLAT_POSITION_PERCENT",
        60: "PRESET_SLAT_POSITION_ANGLE",
        61: "REACTION_WIND_ALARM",
        62: "HEARTBEAT_WIND_ALARM",
        63: "REACTION_ON_RAIN_ALARM",
        64: "HEARTBEAT_RAIN_ALARM",
        65: "REACTION_FROST_ALARM",
        66: "HEARTBEAT_FROST_ALARM",
        67: "MAX_SLAT_MOVE_TIME",
        68: "ENABLE_BLINDS_MODE",
        69: "STORAGE_FUNCTIONS_FOR_SCENE",
    },
    801: {  # Sunblind Sensor Basic
        51: "ENABLE_BLINDS_MODE",
        52: "UP_DOWN_ACTION",
        53: "ENABLE_TOGGLE_MODE",
    },
    "global": {  # Global properties (all objects)
        1: "OBJECT_TYPE",
        2: "OBJECT_NAME",
        3: "SEMAPHOR",
        4: "GROUP_OBJECT_REFERENCE",
        5: "LOAD_STATE_CONTROL",
        6: "RUN_STATE_CONTROL",
        7: "TABLE_REFERENCE",
        8: "SERVICE_CONTROL",
        9: "FIRMWARE_REVISION",
        10: "SERVICES_SUPPORTED",
        11: "SERIAL_NUMBER",
        12: "MANUFACTURER_ID",
        13: "PROGRAM_VERSION",
        14: "DEVICE_CONTROL",
        15: "ORDER_INFO",
        16: "PEI_TYPE",
        17: "PORT_CONFIGURATION",
        18: "POLL_GROUP_SETTINGS",
        19: "MANUFACTURER_DATA",
        20: "ENABLE",
        21: "DESCRIPTION",
        22: "FILE",
        23: "TABLE",
        24: "ENROL",
        25: "VERSION",
        26: "GROUP_OBJECT_LINK",
        27: "MCB_TABLE",
        28: "ERROR_CODE",
        29: "OBJECT_INDEX",
        30: "DOWNLOAD_COUNTER",
    },
}

# Property Data Types
PROP_TYPE_MAP = {
    0x00: "CONTROL",
    0x01: "CHAR",
    0x02: "UNSIGNED_CHAR",
    0x03: "INT",
    0x04: "UNSIGNED_INT",
    0x05: "KNX_FLOAT",
    0x06: "DATE",
    0x07: "TIME",
    0x08: "LONG",
    0x09: "UNSIGNED_LONG",
    0x0A: "FLOAT",
    0x0B: "DOUBLE",
    0x0C: "CHAR_BLOCK",
    0x0D: "POLL_GROUP_SETTINGS",
    0x0E: "SHORT_CHAR_BLOCK",
    0x0F: "DATE_TIME",
    0x10: "VARIABLE_LENGTH",
    0x11: "GENERIC_01",
    0x12: "GENERIC_02",
    0x13: "GENERIC_03",
    0x14: "GENERIC_04",
    0x15: "GENERIC_05",
    0x16: "GENERIC_06",
    0x17: "GENERIC_07",
    0x18: "GENERIC_08",
    0x19: "GENERIC_09",
    0x1A: "GENERIC_10",
    0x1B: "GENERIC_11",
    0x1C: "GENERIC_12",
    0x1D: "GENERIC_13",
    0x1E: "GENERIC_14",
    0x1F: "GENERIC_15",
    0x20: "GENERIC_16",
    0x21: "GENERIC_17",
    0x22: "GENERIC_18",
    0x23: "GENERIC_19",
    0x24: "GENERIC_20",
    0x2F: "UTF-8",
    0x30: "VERSION",
    0x31: "ALARM_INFO",
    0x32: "BINARY_INFORMATION",
    0x33: "BITSET8",
    0x34: "BITSET16",
    0x35: "ENUM8",
    0x36: "SCALING",
    0x3C: "NE_VL",
    0x3D: "NE_FL",
    0x3E: "FUNCTION",
    0x3F: "ESCAPE",
}

# BCU Types (Mask Version -> Name)
BCU_TYPES = {
    0x0010: "BCU 1",
    0x0011: "BCU 1 (extended)",
    0x0012: "BIM M112",
    0x0013: "BCU 1",
    0x0020: "BCU 2",
    0x0021: "BCU 2 (extended)",
    0x0025: "BIM M113",
    0x0300: "BIM M112",
    0x0310: "BIM M112",
    0x0700: "BIM M112 (new)",
    0x0701: "BIM M113 (new)",
    0x0705: "System B",
    0x07B0: "System 300",
    0x0810: "TP-1 (System 7)",
    0x0910: "System 7",
    0x0911: "System 7",
    0x091A: "IP Router",
    0x1012: "KNX IP",
    0x1013: "KNX IP",
    0x17B0: "System B IP",
    0x27B0: "System B IP v2",
    0x5705: "System 7 IP",
    0x57B0: "System B IP (Router)",
}

# Common BCU Keys (factory defaults and common patterns)
COMMON_BCU_KEYS = [
    "FFFFFFFF",  # Universal factory default (most common)
    "00000000",  # Uninitialized/empty
    "11111111",  # Repeating pattern
    "22222222",
    "12345678",  # Sequential
    "87654321",  # Reverse sequential
    "ABCDEFAB",  # Hex pattern
    "DEADBEEF",  # Common test value
    "CAFEBABE",  # Java magic number
    "00000001",  # Common low values
    "00000002",
]

# KNX Property Data Types
DATA_TYPES = {
    0x00: "CONTROL",
    0x01: "CHAR",
    0x02: "UCHAR",
    0x03: "INT",
    0x04: "UINT",
    0x05: "KNX_FLOAT",
    0x06: "DATE",
    0x07: "TIME",
    0x08: "LONG",
    0x09: "ULONG",
    0x0A: "FLOAT",
    0x0B: "DOUBLE",
    0x0C: "CHAR_BLOCK",
    0x0D: "POLL_GRP",
    0x0E: "SHORT_CHAR_BLOCK",
    0x0F: "DATE_TIME",
    0x10: "VAR_LENGTH",
    0x11: "GENERIC_01",
    0x12: "GENERIC_02",
    0x13: "GENERIC_03",
    0x14: "GENERIC_04",
    0x15: "GENERIC_05",
    0x16: "GENERIC_06",
    0x17: "GENERIC_07",
    0x18: "GENERIC_08",
    0x19: "GENERIC_09",
    0x1A: "GENERIC_10",
    0x1B: "GENERIC_11",
    0x1C: "GENERIC_12",
    0x1D: "GENERIC_13",
    0x1E: "GENERIC_14",
    0x1F: "GENERIC_15",
    0x20: "GENERIC_16",
    0x21: "GENERIC_17",
    0x22: "GENERIC_18",
    0x23: "GENERIC_19",
    0x24: "GENERIC_20",
}


def get_vendor_name(vendor_id: int) -> str:
    """Get vendor name from manufacturer ID"""
    return VENDORS.get(vendor_id, f"Unknown ({vendor_id})")


def get_object_type_name(obj_type: int) -> str:
    """Get object type name from type ID"""
    return OBJECT_TYPES.get(obj_type, f"Unknown Object ({obj_type})")


def get_property_name(obj_type: int, prop_id: int) -> str:
    """Get property name from object type and property ID"""
    # Check object-specific properties first
    if obj_type in OBJECT_PROP_TYPES:
        if prop_id in OBJECT_PROP_TYPES[obj_type]:
            return OBJECT_PROP_TYPES[obj_type][prop_id]

    # Fall back to global properties
    if prop_id in OBJECT_PROP_TYPES["global"]:
        return OBJECT_PROP_TYPES["global"][prop_id]

    return f"PID_{prop_id}"


def normalize_descriptor(value):
    """Normalize a DeviceDescriptor value to 2-byte big-endian bytes.

    xknx may return the descriptor as int or bytes depending on version.
    """
    if value is None:
        return None
    if isinstance(value, int):
        return value.to_bytes(2, "big")
    if isinstance(value, (bytes, bytearray)):
        return bytes(value)
    return None


def parse_bcu_type(mask_version) -> str:
    """Parse BCU type from mask version (bytes or int)"""
    if isinstance(mask_version, int):
        mask_version = mask_version.to_bytes(2, "big")
    if not mask_version or len(mask_version) < 2:
        return "Unknown"

    mask = (mask_version[0] << 8) | mask_version[1]

    # Exact match first
    if mask in BCU_TYPES:
        return BCU_TYPES[mask]

    # Match by high byte (BCU family)
    high_byte = mask >> 8
    for key, name in BCU_TYPES.items():
        if (key >> 8) == high_byte:
            return f"{name} (variant 0x{mask:04x})"

    return f"Unknown (0x{mask:04x})"


def get_data_type_name(data_type: int) -> str:
    """Get data type name from type ID"""
    return DATA_TYPES.get(data_type, f"TYPE_{data_type:02X}")
