"""
Test state machine coverage for stateful fuzzers.

Stateful fuzzers (inheriting from StatefulFuzzer) must have:
1. All states reachable via state transitions
2. Requests referencing each defined state
3. Pre-auth requests for connection testing without credentials
4. Post-auth requests for testing after authentication

Applies only to protocols that define state requirements in RequestInfo.

Generated by fuzzer quality audit (2026-02-14).
"""

import pytest

from oida.fuzz.protocols import PROTOCOL_FUZZERS
from oida.fuzz.core.base_fuzzer import CommonState
from tests.service_gate import require_service

pytestmark = pytest.mark.core


def _get_state_info(protocol_name):
    """Extract state information from a protocol's request definitions.

    Returns:
        Tuple of (requests, states_required, categories)
        where states_required is the set of all state strings referenced.
    """
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        return [], set(), set()

    requests = fuzzer_class.get_request_definitions()
    states_required = set()
    categories = set()

    for r in requests:
        categories.add(r.category)
        if r.requires_state is not None:
            if isinstance(r.requires_state, list):
                for s in r.requires_state:
                    states_required.add(s.value if isinstance(s, CommonState) else str(s))
            elif isinstance(r.requires_state, CommonState):
                states_required.add(r.requires_state.value)
            else:
                states_required.add(str(r.requires_state))

    return requests, states_required, categories


# --------------------------------------------------------------------------- #
# Protocols with state requirements (from audit)
# --------------------------------------------------------------------------- #

# Protocols known to use requires_state in their RequestInfo definitions
STATEFUL_PROTOCOLS = {
    # Network/IT protocols
    "ftp": {
        "expected_states": {"PRE_AUTH", "AUTHENTICATED", "ANY"},
        "must_have_pre_auth": True,
        "must_have_post_auth": True,
    },
    "mqtt": {
        "expected_states": {"PRE_AUTH", "AUTHENTICATED", "ANY"},
        "must_have_pre_auth": True,
        "must_have_post_auth": True,
    },
    "vnc": {
        "expected_states": {"PRE_AUTH", "AUTHENTICATED", "ANY"},
        "must_have_pre_auth": True,
        "must_have_post_auth": True,
    },
    "http": {
        "expected_states": {"CONNECTED", "AUTHENTICATED"},
        "must_have_pre_auth": False,
        "must_have_post_auth": False,
    },
    "smtp": {
        "expected_states": {"CONNECTED", "EHLO_SENT", "AUTHENTICATED"},
        "must_have_pre_auth": False,
        "must_have_post_auth": False,
    },
    # ICS/SCADA protocols (audit 2026-02-14)
    "iec104": {
        "expected_states": {"CONNECTED", "ANY"},
        "must_have_pre_auth": False,
        "must_have_post_auth": False,
    },
    "opcua": {
        "expected_states": {"CONNECTED", "HELLO_COMPLETE", "SECURE_CHANNEL", "SESSION_ACTIVE"},
        "must_have_pre_auth": False,
        "must_have_post_auth": False,
    },
    "mms": {
        "expected_states": {"CONNECTED", "COTP_ESTABLISHED", "MMS_ASSOCIATED"},
        "must_have_pre_auth": False,
        "must_have_post_auth": False,
    },
    "ethernetip": {
        "expected_states": {"CONNECTED", "SESSION_REGISTERED", "ANY"},
        "must_have_pre_auth": False,
        "must_have_post_auth": False,
    },
    "ads": {
        "expected_states": {"CONNECTED", "ADS_VALIDATED", "ANY"},
        "must_have_pre_auth": False,
        "must_have_post_auth": False,
    },
}

# Protocols that are StatefulFuzzer subclasses
STATEFUL_FUZZER_SUBCLASSES = {"ftp", "mqtt", "iec104"}


@pytest.mark.parametrize(
    "protocol_name,state_config",
    sorted(STATEFUL_PROTOCOLS.items()),
    ids=sorted(STATEFUL_PROTOCOLS.keys()),
)
def test_stateful_protocol_has_state_requirements(protocol_name, state_config):
    """Stateful protocols must have at least one request with requires_state."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available")

    requests, states_required, _ = _get_state_info(protocol_name)

    assert len(states_required) > 0, (
        f"{protocol_name}: no requests have requires_state set. "
        f"Stateful protocols should have requests in different states. "
        f"Requests: {[(r.name, r.requires_state) for r in requests]}"
    )


@pytest.mark.parametrize(
    "protocol_name,state_config",
    sorted(STATEFUL_PROTOCOLS.items()),
    ids=sorted(STATEFUL_PROTOCOLS.keys()),
)
def test_expected_states_referenced(protocol_name, state_config):
    """All expected states should be referenced by at least one request."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available")

    _, states_required, _ = _get_state_info(protocol_name)
    expected_states = state_config["expected_states"]

    missing = expected_states - states_required
    if missing:
        # Some states might be implicitly handled (e.g., None defaults to
        # AUTHENTICATED). Don't hard-fail, but xfail for documentation.
        pytest.xfail(
            f"{protocol_name}: states {missing} not explicitly referenced "
            f"by any request. Found states: {sorted(states_required)}. "
            f"These may be implicitly covered via default state handling."
        )


@pytest.mark.parametrize(
    "protocol_name,state_config",
    [(name, cfg) for name, cfg in sorted(STATEFUL_PROTOCOLS.items()) if cfg["must_have_pre_auth"]],
    ids=[name for name, cfg in sorted(STATEFUL_PROTOCOLS.items()) if cfg["must_have_pre_auth"]],
)
def test_pre_auth_requests_exist(protocol_name, state_config):
    """Protocols with auth must have pre-auth requests for unauthenticated testing."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available")

    requests = fuzzer_class.get_request_definitions()
    pre_auth_states = {"PRE_AUTH", "CONNECTED", "ANY"}

    has_pre_auth = False
    for r in requests:
        if r.requires_state is None:
            continue
        state_vals = set()
        if isinstance(r.requires_state, list):
            for s in r.requires_state:
                state_vals.add(s.value if isinstance(s, CommonState) else str(s))
        elif isinstance(r.requires_state, CommonState):
            state_vals.add(r.requires_state.value)
        else:
            state_vals.add(str(r.requires_state))

        if state_vals & pre_auth_states:
            has_pre_auth = True
            break

    assert has_pre_auth, (
        f"{protocol_name}: no pre-auth requests found. "
        f"Auth protocols must have requests that run before authentication "
        f"(requires_state=PRE_AUTH, CONNECTED, or ANY). "
        f"States found: {_get_state_info(protocol_name)[1]}"
    )


@pytest.mark.parametrize(
    "protocol_name,state_config",
    [(name, cfg) for name, cfg in sorted(STATEFUL_PROTOCOLS.items()) if cfg["must_have_post_auth"]],
    ids=[name for name, cfg in sorted(STATEFUL_PROTOCOLS.items()) if cfg["must_have_post_auth"]],
)
def test_post_auth_requests_exist(protocol_name, state_config):
    """Protocols with auth must have post-auth requests."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available")

    requests = fuzzer_class.get_request_definitions()
    post_auth_states = {"AUTHENTICATED", "ANY"}

    has_post_auth = False
    for r in requests:
        if r.requires_state is None:
            # None defaults to protocol's DEFAULT_REQUEST_STATE
            # which is typically AUTHENTICATED
            has_post_auth = True
            break
        state_vals = set()
        if isinstance(r.requires_state, list):
            for s in r.requires_state:
                state_vals.add(s.value if isinstance(s, CommonState) else str(s))
        elif isinstance(r.requires_state, CommonState):
            state_vals.add(r.requires_state.value)
        else:
            state_vals.add(str(r.requires_state))

        if state_vals & post_auth_states:
            has_post_auth = True
            break

    assert has_post_auth, (
        f"{protocol_name}: no post-auth requests found. "
        f"Auth protocols must have requests that run after authentication "
        f"(requires_state=AUTHENTICATED or ANY, or None for default)."
    )


# --------------------------------------------------------------------------- #
# StatefulFuzzer subclass checks
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "protocol_name",
    sorted(STATEFUL_FUZZER_SUBCLASSES),
    ids=sorted(STATEFUL_FUZZER_SUBCLASSES),
)
def test_stateful_fuzzer_is_subclass(protocol_name):
    """Protocols marked as stateful actually inherit from StatefulFuzzer."""
    from oida.fuzz.core.stateful_fuzzer import StatefulFuzzer

    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available")

    assert issubclass(fuzzer_class, StatefulFuzzer), (
        f"{protocol_name} should be a StatefulFuzzer subclass but is {fuzzer_class.__bases__}"
    )


@pytest.mark.parametrize(
    "protocol_name",
    sorted(STATEFUL_FUZZER_SUBCLASSES),
    ids=sorted(STATEFUL_FUZZER_SUBCLASSES),
)
def test_stateful_fuzzer_has_multiple_state_phases(protocol_name):
    """StatefulFuzzer subclasses should have requests in 2+ state phases."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available")

    _, states_required, _ = _get_state_info(protocol_name)

    # Filter out ANY since it is not really a distinct phase.
    # ICS protocols like IEC104 legitimately use CONNECTED + ANY because they
    # have no authentication -- their state machine is connect-then-operate.
    # Require 2+ total states (including ANY) to ensure at least some state
    # awareness, but only require 2+ non-ANY phases for auth protocols.
    assert len(states_required) >= 2, (
        f"{protocol_name}: only {len(states_required)} state(s) "
        f"({sorted(states_required)}). StatefulFuzzer should have at least "
        f"2 state references (e.g., CONNECTED + ANY, or PRE_AUTH + AUTHENTICATED)."
    )


# --------------------------------------------------------------------------- #
# Non-stateful protocols should NOT have orphaned state references
# --------------------------------------------------------------------------- #

NON_STATEFUL_WITH_STATES = {"http", "smtp", "vnc", "opcua", "mms"}


@pytest.mark.parametrize(
    "protocol_name",
    sorted(NON_STATEFUL_WITH_STATES),
    ids=sorted(NON_STATEFUL_WITH_STATES),
)
def test_non_stateful_state_references_are_valid(protocol_name):
    """Non-StatefulFuzzer protocols with state refs should use valid state strings."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available")

    _, states_required, _ = _get_state_info(protocol_name)

    for state in states_required:
        # Custom states are allowed (e.g., EHLO_SENT, VERSION_EXCHANGED)
        # but should be documented. Just ensure they are non-empty strings.
        assert state and isinstance(state, str), (
            f"{protocol_name}: invalid state reference: {state!r}. "
            f"States must be non-empty strings."
        )


# --------------------------------------------------------------------------- #
# Coverage summary test (informational)
# --------------------------------------------------------------------------- #


def test_state_coverage_summary():
    """At least 3 network/IT protocols should have state requirements."""
    net_protos = [
        "dns",
        "mdns",
        "dhcp",
        "dhcpv6",
        "http",
        "http2",
        "ftp",
        "smtp",
        "mqtt",
        "coap",
        "ntp",
        "tftp",
        "vnc",
        "snmpv1",
        "snmpv2c",
    ]

    stateful_count = 0
    for proto in net_protos:
        _, states, _ = _get_state_info(proto)
        if states:
            stateful_count += 1

    # At least FTP, MQTT, VNC, HTTP, SMTP should have state requirements
    assert stateful_count >= 3, (
        f"Only {stateful_count} network/IT protocols have state requirements. "
        f"Expected at least 3 (FTP, MQTT, VNC at minimum)."
    )


# --------------------------------------------------------------------------- #
# Transport-layer state coverage (audit 2026-02-14)
# --------------------------------------------------------------------------- #

# TCP defines its own state machine via _define_state_machine(), separate from CommonState
TCP_ALL_STATES = {
    "CLOSED",
    "LISTEN",
    "SYN_SENT",
    "SYN_RECEIVED",
    "ESTABLISHED",
    "FIN_WAIT_1",
    "FIN_WAIT_2",
    "CLOSE_WAIT",
    "CLOSING",
    "LAST_ACK",
    "TIME_WAIT",
}

# States a client-side fuzzer should actively reference
TCP_REQUIRED_STATES = {
    "CLOSED",  # Starting state for SYN
    "ESTABLISHED",  # Data transfer, attacks
    "SYN_SENT",  # After SYN, before SYN-ACK
    "SYN_RECEIVED",  # Server-side response
}

# Passive/intermediate states -- acceptable to have no requires_state
TCP_PASSIVE_STATES = {
    "LISTEN",  # Server-only
    "FIN_WAIT_1",  # Initiated close
    "FIN_WAIT_2",  # Waiting for remote FIN
    "CLOSE_WAIT",  # Waiting for app close
    "CLOSING",  # Simultaneous close
    "LAST_ACK",  # Waiting for final ACK
    "TIME_WAIT",  # Waiting for timeout
}


class TestTCPStateCoverage:
    """TCP fuzzer should reference key states in request definitions."""

    def test_tcp_has_state_aware_requests(self):
        """TCP fuzzer should have requests with requires_state."""
        fuzzer_class = PROTOCOL_FUZZERS.get("tcp")
        if fuzzer_class is None:
            require_service("tcp not available")

        requests = fuzzer_class.get_request_definitions()
        stateful = [r for r in requests if r.requires_state]
        assert len(stateful) > 0, (
            "TCP fuzzer has no requests with requires_state. "
            "TCP is a stateful protocol and should have state-aware requests."
        )

    def test_tcp_required_states_referenced(self):
        """Key TCP states should be referenced by at least one request."""
        fuzzer_class = PROTOCOL_FUZZERS.get("tcp")
        if fuzzer_class is None:
            require_service("tcp not available")

        requests = fuzzer_class.get_request_definitions()
        referenced_states = {
            str(r.requires_state) for r in requests if r.requires_state is not None
        }

        missing = TCP_REQUIRED_STATES - referenced_states
        assert not missing, (
            f"TCP: required states not referenced by any request: {missing}. "
            f"Referenced states: {sorted(referenced_states)}. "
            f"Add requests with requires_state for these states."
        )

    def test_tcp_established_has_multiple_requests(self):
        """ESTABLISHED state should have multiple requests (data transfer phase)."""
        fuzzer_class = PROTOCOL_FUZZERS.get("tcp")
        if fuzzer_class is None:
            require_service("tcp not available")

        requests = fuzzer_class.get_request_definitions()
        established_requests = [r for r in requests if str(r.requires_state) == "ESTABLISHED"]
        assert len(established_requests) >= 3, (
            f"TCP: ESTABLISHED state has only {len(established_requests)} requests. "
            f"Expected at least 3 (data, options, attacks). "
            f"Found: {[r.name for r in established_requests]}"
        )

    def test_tcp_closed_has_syn_request(self):
        """CLOSED state should have at least one SYN request."""
        fuzzer_class = PROTOCOL_FUZZERS.get("tcp")
        if fuzzer_class is None:
            require_service("tcp not available")

        requests = fuzzer_class.get_request_definitions()
        closed_requests = [r for r in requests if str(r.requires_state) == "CLOSED"]
        assert len(closed_requests) >= 1, (
            "TCP: CLOSED state has no requests. SYN handshake should start from CLOSED."
        )
        syn_requests = [r for r in closed_requests if "SYN" in r.name.upper()]
        assert len(syn_requests) >= 1, (
            f"TCP: CLOSED state has no SYN request. Found: {[r.name for r in closed_requests]}"
        )

    def test_tcp_passive_states_documented(self):
        """Unreferenced states should be in the known passive set."""
        fuzzer_class = PROTOCOL_FUZZERS.get("tcp")
        if fuzzer_class is None:
            require_service("tcp not available")

        requests = fuzzer_class.get_request_definitions()
        referenced_states = {
            str(r.requires_state) for r in requests if r.requires_state is not None
        }
        unreferenced = TCP_ALL_STATES - referenced_states

        # All unreferenced states should be in the known passive set
        unexpected = unreferenced - TCP_PASSIVE_STATES
        assert not unexpected, (
            f"TCP: states not referenced by any request and not in known passive set: "
            f"{unexpected}. Either add requests for these states or add them to "
            f"TCP_PASSIVE_STATES if they are intentionally unreferenced."
        )


class TestStatelessProtocolsHaveNoStateRequirements:
    """Non-stateful layer 3/4 protocols should not have requires_state on requests."""

    @pytest.mark.parametrize(
        "protocol_name",
        ["ipv4", "icmp", "icmpv6"],
        ids=["ipv4", "icmp", "icmpv6"],
    )
    def test_stateless_no_requires_state(self, protocol_name):
        """Stateless layer 3/4 protocols should not require specific states."""
        fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
        if fuzzer_class is None:
            require_service(f"{protocol_name} not available")

        requests = fuzzer_class.get_request_definitions()
        stateful = [r for r in requests if r.requires_state]
        assert not stateful, (
            f"{protocol_name}: stateless protocol has {len(stateful)} requests "
            f"with requires_state: {[(r.name, r.requires_state) for r in stateful]}. "
            f"This is unexpected for a stateless protocol."
        )


# --------------------------------------------------------------------------- #
# ICS/SCADA state coverage (audit 2026-02-14)
# --------------------------------------------------------------------------- #

# ICS protocols that are inherently stateless (no state machine)
ICS_STATELESS_PROTOCOLS = [
    "modbus",
    "modbus_rtu",
    "dnp3",
    "bacnet",
]


class TestICSStateCoverage:
    """ICS/SCADA protocol state machine coverage."""

    def test_iec104_is_stateful(self):
        """IEC 104 must be a StatefulFuzzer -- it has STARTDT/STOPDT state."""
        from oida.fuzz.core.stateful_fuzzer import StatefulFuzzer

        fuzzer_class = PROTOCOL_FUZZERS.get("iec104")
        if fuzzer_class is None:
            require_service("iec104 not available")

        assert issubclass(fuzzer_class, StatefulFuzzer), (
            "IEC 104 should be a StatefulFuzzer subclass for STARTDT/STOPDT handling"
        )

    def test_iec104_has_connected_state_requests(self):
        """IEC 104 must have requests that run in CONNECTED state."""
        fuzzer_class = PROTOCOL_FUZZERS.get("iec104")
        if fuzzer_class is None:
            require_service("iec104 not available")

        requests = fuzzer_class.get_request_definitions()
        connected_reqs = [
            r
            for r in requests
            if r.requires_state and str(r.requires_state) == "CommonState.CONNECTED"
        ]
        assert len(connected_reqs) >= 1, (
            "IEC 104: no requests in CONNECTED state. "
            "Baseline/connection requests need CONNECTED state."
        )

    def test_iec104_has_any_state_requests(self):
        """IEC 104 should have requests usable in ANY state for general fuzzing."""
        fuzzer_class = PROTOCOL_FUZZERS.get("iec104")
        if fuzzer_class is None:
            require_service("iec104 not available")

        requests = fuzzer_class.get_request_definitions()
        any_reqs = [
            r for r in requests if r.requires_state and str(r.requires_state) == "CommonState.ANY"
        ]
        assert len(any_reqs) >= 5, (
            f"IEC 104: only {len(any_reqs)} requests in ANY state, expected >= 5. "
            f"Most IEC 104 data types should be testable in ANY state."
        )

    def test_opcua_multi_phase_state_machine(self):
        """OPC UA must have requests across all 4 connection phases."""
        fuzzer_class = PROTOCOL_FUZZERS.get("opcua")
        if fuzzer_class is None:
            require_service("opcua not available")

        requests = fuzzer_class.get_request_definitions()
        states = set()
        for r in requests:
            if r.requires_state:
                states.add(
                    r.requires_state.value
                    if isinstance(r.requires_state, CommonState)
                    else str(r.requires_state)
                )

        expected = {"CONNECTED", "HELLO_COMPLETE", "SECURE_CHANNEL", "SESSION_ACTIVE"}
        missing = expected - states
        assert not missing, (
            f"OPC UA: missing states {missing}. "
            f"All 4 phases (CONNECTED, HELLO_COMPLETE, SECURE_CHANNEL, SESSION_ACTIVE) "
            f"must be covered. Found: {sorted(states)}"
        )

    def test_opcua_session_active_has_most_requests(self):
        """SESSION_ACTIVE should have the most requests (main operation phase)."""
        fuzzer_class = PROTOCOL_FUZZERS.get("opcua")
        if fuzzer_class is None:
            require_service("opcua not available")

        requests = fuzzer_class.get_request_definitions()
        session_reqs = [r for r in requests if str(r.requires_state) == "SESSION_ACTIVE"]
        assert len(session_reqs) >= 8, (
            f"OPC UA: SESSION_ACTIVE has only {len(session_reqs)} requests. "
            f"Expected >= 8 (read, browse, write, subscribe, etc.). "
            f"Found: {[r.name for r in session_reqs]}"
        )

    def test_mms_three_phase_state_machine(self):
        """MMS must have requests across CONNECTED, COTP_ESTABLISHED, MMS_ASSOCIATED."""
        fuzzer_class = PROTOCOL_FUZZERS.get("mms")
        if fuzzer_class is None:
            require_service("mms not available")

        requests = fuzzer_class.get_request_definitions()
        states = set()
        for r in requests:
            if r.requires_state:
                states.add(str(r.requires_state))

        expected = {"CONNECTED", "COTP_ESTABLISHED", "MMS_ASSOCIATED"}
        missing = expected - states
        assert not missing, (
            f"MMS: missing states {missing}. "
            f"All 3 phases (CONNECTED, COTP_ESTABLISHED, MMS_ASSOCIATED) "
            f"must be covered. Found: {sorted(states)}"
        )

    def test_mms_associated_has_service_requests(self):
        """MMS_ASSOCIATED phase should have read, write, and control requests."""
        fuzzer_class = PROTOCOL_FUZZERS.get("mms")
        if fuzzer_class is None:
            require_service("mms not available")

        requests = fuzzer_class.get_request_definitions()
        assoc_reqs = [r for r in requests if str(r.requires_state) == "MMS_ASSOCIATED"]
        assert len(assoc_reqs) >= 4, (
            f"MMS: MMS_ASSOCIATED has only {len(assoc_reqs)} requests. "
            f"Expected >= 4 (read, write, control, file). "
            f"Found: {[r.name for r in assoc_reqs]}"
        )

    @pytest.mark.parametrize(
        "protocol_name",
        ICS_STATELESS_PROTOCOLS,
        ids=ICS_STATELESS_PROTOCOLS,
    )
    def test_ics_stateless_protocols_have_no_state(self, protocol_name):
        """ICS protocols without state machines should have no requires_state."""
        fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
        if fuzzer_class is None:
            require_service(f"{protocol_name} not available")

        requests = fuzzer_class.get_request_definitions()
        stateful = [r for r in requests if r.requires_state]
        assert not stateful, (
            f"{protocol_name}: expected stateless but found {len(stateful)} requests "
            f"with requires_state: {[(r.name, str(r.requires_state)) for r in stateful]}. "
            f"If this protocol needs a state machine, add it to STATEFUL_PROTOCOLS."
        )
