"""
Test that each fuzzer meets minimum request count for its tier.

Tier thresholds:
- P0 (Critical ICS): 8+ requests
- P1 (Critical IoT/Net): 8+ requests
- P2 (Standard): 5+ requests
- P3 (Simple/Niche): 3+ requests

Generated by fuzzer quality audit (2026-02-14).
Thresholds are derived from actual request counts -- these tests codify
the current baseline and flag regressions.
"""

import pytest

from oida.fuzz.protocols import PROTOCOL_FUZZERS
from tests.service_gate import require_service

pytestmark = pytest.mark.core

# Full tier mapping for all protocols
ALL_PROTOCOL_TIERS = {
    # P0 - Critical ICS
    "modbus": ("P0", 8),
    "modbus_rtu": ("P0", 8),
    "opcua": ("P0", 8),
    "iec104": ("P0", 8),
    "mms": ("P0", 8),
    "dnp3": ("P0", 8),
    "ethernetip": ("P0", 8),
    "bacnet": ("P0", 8),
    "ads": ("P0", 8),
    # P1 - Critical IoT/Net
    "mqtt": ("P1", 8),
    "http": ("P1", 8),
    "http2": ("P1", 8),
    "dns": ("P1", 8),
    "ftp": ("P1", 8),
    "smtp": ("P1", 8),
    # P2 - Standard
    "coap": ("P2", 5),
    "dhcp": ("P2", 5),
    "dhcpv6": ("P2", 5),
    "ntp": ("P2", 5),
    "hl7": ("P2", 5),
    "vnc": ("P2", 5),
    # P3 - Simple/Niche
    "echo": ("P3", 3),
    "daytime": ("P3", 3),
    "tftp": ("P3", 3),
    "mdns": ("P3", 3),
    "snmpv1": ("P1", 8),
    "snmpv2c": ("P1", 8),
    "icmp": ("P3", 3),
    "icmpv6": ("P3", 3),
    "ipv4": ("P3", 3),
    "tcp": ("P3", 3),
    # Special
    "mutation": ("N/A", 1),
}

# --------------------------------------------------------------------------- #
# Network/IT protocols covered by the quality audit (2026-02-14)
# These have verified request counts from the audit report.
# --------------------------------------------------------------------------- #
NETWORK_IT_TIERS = {
    # P1 protocols
    "dns": ("P1", 8),
    "http": ("P1", 8),
    "http2": ("P1", 8),
    "ftp": ("P1", 8),
    "smtp": ("P1", 8),
    "mqtt": ("P1", 8),
    "snmpv1": ("P1", 8),
    "snmpv2c": ("P1", 8),
    # P2 protocols
    "coap": ("P2", 5),
    "dhcp": ("P2", 5),
    "dhcpv6": ("P2", 5),
    "ntp": ("P2", 5),
    "vnc": ("P2", 5),
    # P3 protocols
    "mdns": ("P3", 3),
    "tftp": ("P3", 3),
}

# --------------------------------------------------------------------------- #
# Transport & network-layer protocols covered by audit (2026-02-14)
# --------------------------------------------------------------------------- #
TRANSPORT_LAYER_TIERS = {
    "tcp": ("P3", 3),
    "ipv4": ("P3", 3),
    "icmp": ("P3", 3),
    "icmpv6": ("P3", 3),
}

# Exact request counts from audit (used for regression checks)
# Updated 2026-02-14 with current actual counts
AUDIT_REQUEST_COUNTS = {
    "dns": 68,
    "mdns": 20,
    "dhcp": 19,
    "dhcpv6": 16,
    "http": 18,
    "http2": 21,
    "ftp": 16,
    "smtp": 12,
    "mqtt": 12,
    "coap": 20,
    "ntp": 20,
    "tftp": 8,
    "vnc": 15,
    "snmpv1": 13,
    "snmpv2c": 12,
    # Transport/network layer (audited 2026-02-14)
    "tcp": 20,
    "ipv4": 17,
    "icmp": 15,
    "icmpv6": 36,
}

# ICS/SCADA protocols covered by ICS audit (2026-02-14)
ICS_SCADA_TIERS = {
    # P0 - Critical ICS
    "modbus": ("P0", 8),
    "modbus_rtu": ("P0", 8),
    "opcua": ("P0", 8),
    "iec104": ("P0", 8),
    "mms": ("P0", 8),
    "dnp3": ("P0", 8),
    "ethernetip": ("P0", 8),
    "bacnet": ("P0", 8),
    "ads": ("P0", 8),
    # P2 - Healthcare/Other
    "hl7": ("P2", 5),
    # P3 - Simple
    "echo": ("P3", 3),
    "daytime": ("P3", 3),
    "mutation": ("N/A", 1),
}

# Exact ICS request counts. Updated 2026-06-02 after the §4.1 fuzzer
# optimization workflow: dnp3/iec104/opcua gained new Request objects
# (10->13, 12->13, 21->22); other §4.1 items modified primitives inside
# existing Requests (Group expansions, fuzzable= flips, max_len caps,
# annotation passes) so the *count* of registered Requests is unchanged.
ICS_AUDIT_REQUEST_COUNTS = {
    "modbus": 15,
    # 12 -> 11: removed phantom RTU_Combined_Attacks (advertised but never
    # built or connected).
    "modbus_rtu": 11,
    "dnp3": 13,
    "iec104": 13,
    # OPCUA: 22 + 3 (§4 sweep 2026-06-03: NodeIdEncodingOverflow,
    # MalformedCert, State_Confusion).
    "opcua": 25,
    "bacnet": 13,
    # 12 -> 11: removed phantom EIP_CIP_Boundary (advertised but never built
    # or connected).
    "ethernetip": 11,
    "mms": 14,
    "ads": 12,
    "snmpv2c": 12,
    "snmpv3": 12,
    "hl7": 13,
    "mqtt": 14,
    "coap": 20,
    # The following entries were removed (2026-06-03):
    # fins, tase2, profinet_dcp, industrial_ethernet, hartip - no
    # corresponding fuzzer source exists in src/oida/fuzz/protocols/;
    # the tests were unconditionally skipping. These are
    # "implement-or-delete"; deleted here, can be re-added once the
    # underlying fuzzer modules land.
}

# Combine for backward compatibility
PROTOCOL_TIERS = {**ICS_SCADA_TIERS, **NETWORK_IT_TIERS, **TRANSPORT_LAYER_TIERS}


# --------------------------------------------------------------------------- #
# Tests
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "protocol_name,tier_info",
    sorted(PROTOCOL_TIERS.items()),
    ids=sorted(PROTOCOL_TIERS.keys()),
)
def test_minimum_request_count(protocol_name, tier_info):
    """Each fuzzer meets minimum request count for its tier."""
    tier_name, min_requests = tier_info

    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    assert len(requests) >= min_requests, (
        f"{protocol_name} (tier {tier_name}) has {len(requests)} requests, "
        f"minimum is {min_requests}. "
        f"Request names: {[r.name for r in requests]}"
    )


@pytest.mark.parametrize(
    "protocol_name",
    sorted(PROTOCOL_TIERS.keys()),
    ids=sorted(PROTOCOL_TIERS.keys()),
)
def test_request_definitions_have_required_fields(protocol_name):
    """Every RequestInfo has name, description, and category."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    for req in requests:
        assert req.name, f"{protocol_name}: request has empty name"
        assert req.description, f"{protocol_name}: request '{req.name}' has empty description"
        assert req.category, f"{protocol_name}: request '{req.name}' has empty category"


@pytest.mark.parametrize(
    "protocol_name",
    sorted(PROTOCOL_TIERS.keys()),
    ids=sorted(PROTOCOL_TIERS.keys()),
)
def test_request_names_are_unique(protocol_name):
    """Request names must be unique within a fuzzer."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    names = [r.name for r in requests]
    duplicates = [n for n in names if names.count(n) > 1]
    assert not duplicates, f"{protocol_name}: duplicate request names: {set(duplicates)}"


@pytest.mark.parametrize(
    "protocol_name,expected_count",
    sorted(AUDIT_REQUEST_COUNTS.items()),
    ids=sorted(AUDIT_REQUEST_COUNTS.keys()),
)
def test_request_count_no_regression(protocol_name, expected_count):
    """Request count should not decrease from the audited baseline.

    If a request is intentionally removed, update AUDIT_REQUEST_COUNTS.
    """
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    assert len(requests) >= expected_count, (
        f"{protocol_name}: request count regressed from {expected_count} "
        f"to {len(requests)}. If requests were intentionally removed, "
        f"update AUDIT_REQUEST_COUNTS in this test file."
    )


@pytest.mark.parametrize(
    "protocol_name",
    sorted(NETWORK_IT_TIERS.keys()),
    ids=sorted(NETWORK_IT_TIERS.keys()),
)
def test_network_protocol_registered(protocol_name):
    """Every audited network/IT protocol is in PROTOCOL_FUZZERS."""
    if protocol_name not in PROTOCOL_FUZZERS:
        require_service(
            f"{protocol_name} not available in PROTOCOL_FUZZERS (missing optional dep?)"
        )

    fuzzer_class = PROTOCOL_FUZZERS[protocol_name]
    requests = fuzzer_class.get_request_definitions()
    assert requests, f"{protocol_name}: registered fuzzer returns no request definitions"


# --------------------------------------------------------------------------- #
# Transport & network-layer protocol tests (audit 2026-02-14)
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "protocol_name",
    sorted(TRANSPORT_LAYER_TIERS.keys()),
    ids=sorted(TRANSPORT_LAYER_TIERS.keys()),
)
def test_transport_protocol_registered(protocol_name):
    """Every audited transport/network protocol is in PROTOCOL_FUZZERS."""
    assert protocol_name in PROTOCOL_FUZZERS, (
        f"{protocol_name} is not registered in PROTOCOL_FUZZERS. "
        f"Check src/oida/fuzz/protocols/__init__.py"
    )


@pytest.mark.parametrize(
    "protocol_name,tier_info",
    sorted(TRANSPORT_LAYER_TIERS.items()),
    ids=sorted(TRANSPORT_LAYER_TIERS.keys()),
)
def test_transport_minimum_request_count(protocol_name, tier_info):
    """Transport/network fuzzers meet tier P3 minimum (3 requests)."""
    tier_name, min_requests = tier_info

    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    assert len(requests) >= min_requests, (
        f"{protocol_name} (tier {tier_name}) has {len(requests)} requests, "
        f"minimum is {min_requests}."
    )


@pytest.mark.parametrize(
    "protocol_name,expected_count",
    [
        ("tcp", 20),
        ("ipv4", 17),
        ("icmp", 15),
        ("icmpv6", 36),
    ],
    ids=["tcp", "ipv4", "icmp", "icmpv6"],
)
def test_transport_request_count_no_regression(protocol_name, expected_count):
    """Transport/network fuzzer request counts should not decrease.

    Counts updated 2026-02-14 to match current actuals.
    """
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    assert len(requests) >= expected_count, (
        f"{protocol_name}: request count regressed from {expected_count} "
        f"to {len(requests)}. Update if intentional."
    )


# --------------------------------------------------------------------------- #
# ICS/SCADA protocol tests (audit 2026-02-14)
# --------------------------------------------------------------------------- #

ICS_PROTOCOL_NAMES = sorted(ICS_SCADA_TIERS.keys() - {"mutation", "echo", "daytime"})


@pytest.mark.parametrize(
    "protocol_name",
    ICS_PROTOCOL_NAMES,
    ids=ICS_PROTOCOL_NAMES,
)
def test_ics_protocol_registered(protocol_name):
    """Every audited ICS/SCADA protocol is in PROTOCOL_FUZZERS."""
    if protocol_name not in PROTOCOL_FUZZERS:
        require_service(
            f"{protocol_name} not available in PROTOCOL_FUZZERS (missing optional dep?)"
        )

    fuzzer_class = PROTOCOL_FUZZERS[protocol_name]
    requests = fuzzer_class.get_request_definitions()
    assert requests, f"{protocol_name}: registered fuzzer returns no request definitions"


@pytest.mark.parametrize(
    "protocol_name,expected_count",
    sorted(ICS_AUDIT_REQUEST_COUNTS.items()),
    ids=sorted(ICS_AUDIT_REQUEST_COUNTS.keys()),
)
def test_ics_request_count_no_regression(protocol_name, expected_count):
    """ICS/SCADA fuzzer request counts should not decrease from audited baseline.

    If requests are intentionally removed, update ICS_AUDIT_REQUEST_COUNTS.
    """
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    assert len(requests) >= expected_count, (
        f"{protocol_name}: request count regressed from {expected_count} "
        f"to {len(requests)}. If requests were intentionally removed, "
        f"update ICS_AUDIT_REQUEST_COUNTS in this test file."
    )


@pytest.mark.parametrize(
    "protocol_name",
    ICS_PROTOCOL_NAMES,
    ids=ICS_PROTOCOL_NAMES,
)
def test_ics_request_definitions_valid(protocol_name):
    """ICS fuzzer requests have valid name, description, and category."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        require_service(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    for req in requests:
        assert req.name, f"{protocol_name}: request has empty name"
        assert req.description, f"{protocol_name}: request '{req.name}' has empty description"
        assert req.category, f"{protocol_name}: request '{req.name}' has empty category"
