"""
Test primitive type usage in protocol fuzzers.

Validates that fuzzers use the correct boofuzz primitive types:
- No raw String() usage (use SmartString or ReducedString instead)
- No SmartString(GENERIC) where ReducedString would suffice
- SmartString context matches field semantics (PATH for paths, CREDENTIAL for auth)
- Numeric primitive types match field widths

Generated by fuzzer quality audit (2026-02-14).
"""

import os
import re

import pytest

from oida.fuzz.protocols import PROTOCOL_FUZZERS
from tests.service_gate import require_service

pytestmark = pytest.mark.core

# Root of the source tree
_SRC_ROOT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
    "src",
)


def _read_fuzzer_source(protocol_name):
    """Read all source files for a given protocol fuzzer.

    For subpackage fuzzers (e.g., modbus/tcp.py, modbus/pdu.py), reads all
    .py files in the package directory and concatenates them. This ensures
    that shared code (like modbus/pdu.py containing SmartString usage) is
    included in the analysis even when the fuzzer class lives in a specific
    submodule (modbus/tcp.py).

    Returns the combined source code as a string, or None if not found.
    """
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        return None

    module = fuzzer_class.__module__
    parts = module.split(".")

    # Try direct file path from module
    fpath = os.path.join(_SRC_ROOT, *parts) + ".py"
    if os.path.exists(fpath):
        # Check if this file is part of a package (has sibling .py files)
        parent_dir = os.path.dirname(fpath)
        init_file = os.path.join(parent_dir, "__init__.py")
        if os.path.exists(init_file) and parent_dir != os.path.join(
            _SRC_ROOT, "oida", "fuzz", "protocols"
        ):
            # This is a subpackage (e.g., modbus/) -- read all .py files
            combined = []
            for fname in sorted(os.listdir(parent_dir)):
                if fname.endswith(".py"):
                    with open(os.path.join(parent_dir, fname)) as f:
                        combined.append(f.read())
            return "\n".join(combined)
        else:
            with open(fpath) as f:
                return f.read()

    # Try as package -- read all .py files in the package directory
    pkg_dir = os.path.join(_SRC_ROOT, *parts)
    if os.path.isdir(pkg_dir):
        combined = []
        for fname in sorted(os.listdir(pkg_dir)):
            if fname.endswith(".py"):
                with open(os.path.join(pkg_dir, fname)) as f:
                    combined.append(f.read())
        if combined:
            return "\n".join(combined)

    return None


# ---------------------------------------------------------------------------
# All protocol names to test
# ---------------------------------------------------------------------------
ALL_PROTOCOLS = sorted(p for p in PROTOCOL_FUZZERS.keys() if p != "mutation")


# ---------------------------------------------------------------------------
# Test: No raw String() usage
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("protocol_name", ALL_PROTOCOLS, ids=ALL_PROTOCOLS)
def test_no_raw_string_usage(protocol_name):
    """Protocol fuzzers should not use raw boofuzz String().

    Raw String() generates ~1800 mutations including XSS, SQL injection, and
    web payloads that are irrelevant to protocol fuzzing. Use SmartString()
    or ReducedString() instead.
    """
    source = _read_fuzzer_source(protocol_name)
    if source is None:
        require_service(f"Could not read source for {protocol_name}")

    # Match String( but not SmartString(, ReducedString(, RadamsaString(
    raw_string_matches = re.findall(
        r"(?<!Smart)(?<!Reduced)(?<!Radamsa)(?<!\")\bString\(",
        source,
    )

    # Filter out false positives: imports, comments, string type annotations
    real_matches = []
    for match in raw_string_matches:
        idx = source.find(match)
        if idx < 0:
            continue
        line_start = source.rfind("\n", 0, idx) + 1
        line_end = source.find("\n", idx)
        line = source[line_start:line_end]
        stripped = line.strip()

        # Skip comments
        if stripped.startswith("#"):
            continue
        # Skip imports
        if "import" in stripped:
            continue
        # Skip type annotations and docstrings
        if "str" in stripped.lower() and "String(" not in stripped:
            continue

        real_matches.append(stripped)

    assert not real_matches, (
        f"{protocol_name}: found {len(real_matches)} raw String() usage(s). "
        f"Use SmartString() or ReducedString() instead.\n"
        f"Lines: {real_matches[:5]}"
    )


# ---------------------------------------------------------------------------
# Test: SmartString has context when field semantics are clear
#
# These map protocols to the StringContext values they ACTUALLY use today.
# This test codifies the current baseline and flags regressions.
# ---------------------------------------------------------------------------

EXPECTED_CONTEXTS = {
    "ftp": {"PATH", "CREDENTIAL", "COMMAND"},
    "http": {"PATH", "HOST"},
    "smtp": {"CREDENTIAL", "HOSTNAME"},
    "mqtt": {"CREDENTIAL"},
    "opcua": {"CREDENTIAL"},
    "tftp": {"FILENAME"},
    "vnc": {"NUMERIC"},
}


@pytest.mark.parametrize(
    "protocol_name,expected_contexts",
    sorted(EXPECTED_CONTEXTS.items()),
    ids=sorted(EXPECTED_CONTEXTS.keys()),
)
def test_smart_string_has_appropriate_context(protocol_name, expected_contexts):
    """Fuzzers with clear field semantics should use SmartString with context.

    When a field is a path, credential, hostname, etc., the SmartString
    should use the appropriate StringContext for targeted mutations.
    """
    source = _read_fuzzer_source(protocol_name)
    if source is None:
        require_service(f"Could not read source for {protocol_name}")

    found_contexts = set()
    for ctx in [
        "PATH",
        "FILENAME",
        "CREDENTIAL",
        "HOST",
        "HOSTNAME",
        "IP_ADDRESS",
        "PORT",
        "COMMAND",
        "GENERIC",
        "NUMERIC",
    ]:
        pattern = rf"StringContext\.{ctx}"
        if re.search(pattern, source):
            found_contexts.add(ctx)

    missing = expected_contexts - found_contexts
    assert not missing, (
        f"{protocol_name}: expected SmartString contexts {missing} "
        f"but found only {sorted(found_contexts)}. "
        f"Fields with clear semantics should use context-aware mutations."
    )


# ---------------------------------------------------------------------------
# Test: SmartString(GENERIC) should be rare
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("protocol_name", ALL_PROTOCOLS, ids=ALL_PROTOCOLS)
def test_limited_generic_context(protocol_name):
    """SmartString(GENERIC) should be rare -- prefer specific contexts.

    GENERIC context adds overhead over ReducedString with no benefit.
    More than 10 GENERIC usages in one fuzzer suggests missing context analysis.
    """
    source = _read_fuzzer_source(protocol_name)
    if source is None:
        require_service(f"Could not read source for {protocol_name}")

    generic_count = len(re.findall(r"StringContext\.GENERIC", source))

    # Allow up to 10 GENERIC usages per fuzzer
    assert generic_count <= 10, (
        f"{protocol_name}: {generic_count} SmartString(GENERIC) usages. "
        f"Consider using specific StringContext (PATH, CREDENTIAL, HOST, etc.) "
        f"or ReducedString for generic fields. Max allowed: 10."
    )


# ---------------------------------------------------------------------------
# Test: Protocol fuzzers use SmartString (not just static/byte)
#
# Some protocols (modbus, modbus_rtu) use SmartString in subpackage files
# (e.g., modbus/pdu.py). The _read_fuzzer_source helper reads all .py files
# in the package, so these should be detected.
#
# Protocols exempt from SmartString requirement: those that are purely
# binary-field protocols where SmartString adds no value (all fields are
# fixed-width numeric types).
# ---------------------------------------------------------------------------

# Protocols exempt from SmartString requirement
SMART_STRING_EXEMPT = {
    "mutation",  # Generic mutation fuzzer, no protocol-specific fields
}

SMART_STRING_EXPECTED = sorted(p for p in PROTOCOL_FUZZERS.keys() if p not in SMART_STRING_EXEMPT)


@pytest.mark.parametrize(
    "protocol_name",
    SMART_STRING_EXPECTED,
    ids=SMART_STRING_EXPECTED,
)
def test_fuzzer_uses_smart_string(protocol_name):
    """Every non-trivial fuzzer should use SmartString for at least one field.

    SmartString provides protocol-relevant mutations including Radamsa
    integration. Fuzzers using only Static/Byte/Word miss important
    mutation-based bug classes.
    """
    source = _read_fuzzer_source(protocol_name)
    if source is None:
        require_service(f"Could not read source for {protocol_name}")

    has_smart = "SmartString(" in source or "SmartString " in source
    has_smart_bytes = "SmartBytes(" in source or "SmartBytes " in source

    assert has_smart or has_smart_bytes, (
        f"{protocol_name}: no SmartString or SmartBytes usage found. "
        f"Every fuzzer should use SmartString for at least one variable-length "
        f"field to get protocol-relevant mutations and Radamsa integration."
    )


# ---------------------------------------------------------------------------
# Test: Fuzzers import from correct primitive modules
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("protocol_name", ALL_PROTOCOLS, ids=ALL_PROTOCOLS)
def test_no_direct_boofuzz_string_import(protocol_name):
    """Protocol fuzzers should not import String from boofuzz directly.

    The project provides SmartString and ReducedString as replacements.
    Importing raw String from boofuzz suggests unintended usage.
    """
    source = _read_fuzzer_source(protocol_name)
    if source is None:
        require_service(f"Could not read source for {protocol_name}")

    # Check for "from boofuzz import ... String ..." but not "SmartString"
    boofuzz_imports = re.findall(r"from boofuzz import .*", source)
    for imp in boofuzz_imports:
        # Extract imported names
        names = imp.replace("from boofuzz import", "").strip()
        # Remove parentheses for multi-line imports
        names = names.replace("(", "").replace(")", "")
        # Split by comma
        imported = [n.strip() for n in names.split(",")]
        # Check for bare "String" import
        bare_string = any(name == "String" or name.startswith("String ") for name in imported)
        assert not bare_string, (
            f"{protocol_name}: imports raw 'String' from boofuzz. "
            f"Use SmartString from ..primitives.dynamic or "
            f"ReducedString from ..primitives.reduced_string instead.\n"
            f"Import line: {imp}"
        )
