"""
Test that multi-category protocols have requests in all required categories.

Each protocol fuzzer should cover multiple attack categories:
- baseline: at least one connectivity/valid-packet request
- boundary or overflow: at least one boundary/overflow test for numeric protocols
- attack/injection/cve: at least one attack-oriented request for protocols with known CVEs

Protocols with fewer than 3 requests are exempt from balance checks.

Generated by fuzzer quality audit (2026-02-14).
Thresholds derived from actual category distributions in the codebase.
"""

import pytest

from oida.fuzz.protocols import PROTOCOL_FUZZERS

pytestmark = pytest.mark.core


# --------------------------------------------------------------------------- #
# Required categories per protocol
#
# These are the minimum set of categories every protocol should have.
# Derived from the audit: if a protocol has 5+ requests, it should cover
# at least the categories listed here.
# --------------------------------------------------------------------------- #
REQUIRED_CATEGORIES = {
    # ICS/SCADA P0 protocols (from ICS audit 2026-02-14)
    "modbus": {"baseline", "read", "write", "boundary"},
    "modbus_rtu": {"baseline", "read", "write", "boundary"},
    "opcua": {"baseline", "read", "write", "attack"},
    "iec104": {"baseline", "read", "write", "attacks"},
    "mms": {"baseline", "read", "write", "crash"},
    "dnp3": {"baseline", "read", "write", "boundary"},
    "ethernetip": {"baseline", "read", "write", "boundary"},
    "bacnet": {"baseline", "read", "write", "overflow"},
    "ads": {"baseline", "read", "write", "boundary"},
    "fins": {"read", "boundary", "high_crash"},
    # ICS/SCADA P2 protocols
    "tase2": {"baseline", "attacks", "malformed"},
    "hartip": {"baseline", "read", "write", "overflow"},
    "profinet_dcp": {"baseline", "read", "write", "overflow"},
    "industrial_ethernet": {"baseline", "standard", "overflow"},
    # Healthcare/specialty (from earlier audit)
    "hl7": {"baseline", "overflow"},
    "dicom": {"baseline", "attacks"},
    "echo": {"baseline", "overflow"},
    "daytime": {"baseline", "overflow"},
    # Network/IT protocols (from 2026-02-14 audit)
    "dns": {"baseline", "standard", "overflow"},
    "mdns": {"quick_coverage", "query", "response"},
    "dhcp": {"baseline", "standard", "overflow"},
    "dhcpv6": {"baseline", "standard", "overflow"},
    "http": {"baseline", "core", "edge_cases"},
    "http2": {"baseline", "standard", "headers"},
    "ftp": {"baseline", "auth", "navigation"},
    "smtp": {"baseline", "core", "auth", "overflow", "boundary"},
    "mqtt": {"baseline", "auth", "boundary"},
    "coap": {"quick_coverage", "standard", "boundary"},
    "ntp": {"standard", "boundary", "control"},
    "tftp": {"baseline", "standard", "overflow", "boundary", "cve"},
    "vnc": {"baseline", "auth", "postauth", "overflow", "boundary"},
    "snmpv1": {"standard", "high_crash", "boundary"},
    "snmpv2c": {"standard", "high_crash", "boundary"},
}

# Minimum number of distinct categories for multi-request fuzzers
MIN_CATEGORIES_FOR_MULTI_REQUEST = 2

# Protocols that should have overflow/boundary category (numeric fields present)
OVERFLOW_EXPECTED = {
    "dns",
    "dhcp",
    "http",
    "http2",
    "mqtt",
    "coap",
    "ntp",
    "tftp",
    "snmpv1",
    "snmpv2c",
    "vnc",
    "ads",
    "hl7",
    "echo",
    "daytime",
    # ICS protocols with numeric length/count fields
    "modbus",
    "modbus_rtu",
    "dnp3",
    "ethernetip",
    "bacnet",
    "mms",
    "hartip",
    "profinet_dcp",
    "industrial_ethernet",
}

# Protocols that should have auth/security category
AUTH_EXPECTED = {
    "ftp",
    "smtp",
    "mqtt",
    "vnc",
    "http2",
    "ntp",
    # ICS protocols with authentication
    "opcua",
    "iec104",
    "ads",
    "fins",
    "mms",
    "tase2",
    "hartip",
    "ethernetip",
}


@pytest.mark.parametrize(
    "protocol_name,required_cats",
    sorted(REQUIRED_CATEGORIES.items()),
    ids=sorted(REQUIRED_CATEGORIES.keys()),
)
def test_required_categories_present(protocol_name, required_cats):
    """Protocol fuzzer covers all required categories."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        pytest.skip(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    actual_cats = {r.category for r in requests}

    missing = required_cats - actual_cats
    assert not missing, (
        f"{protocol_name}: missing required categories: {missing}. "
        f"Found categories: {sorted(actual_cats)}. "
        f"Requests: {[(r.name, r.category) for r in requests]}"
    )


@pytest.mark.parametrize(
    "protocol_name",
    sorted(REQUIRED_CATEGORIES.keys()),
    ids=sorted(REQUIRED_CATEGORIES.keys()),
)
def test_multi_request_fuzzers_have_category_diversity(protocol_name):
    """Fuzzers with 5+ requests should have at least 2 distinct categories."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        pytest.skip(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    if len(requests) < 5:
        pytest.skip(f"{protocol_name} has only {len(requests)} requests, skipping diversity check")

    actual_cats = {r.category for r in requests}
    assert len(actual_cats) >= MIN_CATEGORIES_FOR_MULTI_REQUEST, (
        f"{protocol_name}: only {len(actual_cats)} category(ies) "
        f"({sorted(actual_cats)}) across {len(requests)} requests. "
        f"Expected at least {MIN_CATEGORIES_FOR_MULTI_REQUEST} distinct categories."
    )


@pytest.mark.parametrize(
    "protocol_name",
    sorted(REQUIRED_CATEGORIES.keys()),
    ids=sorted(REQUIRED_CATEGORIES.keys()),
)
def test_baseline_request_exists(protocol_name):
    """Every multi-request fuzzer should have at least one baseline request.

    Accepts 'baseline' or 'quick_coverage' as baseline categories.
    Protocols with fewer than 3 requests are exempt.
    """
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        pytest.skip(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    if len(requests) < 3:
        pytest.skip(f"{protocol_name} has <3 requests, baseline not required")

    baseline_cats = {"baseline", "quick_coverage", "discovery", "standard"}
    has_baseline = any(r.category in baseline_cats for r in requests)

    # Some protocols use the first request as an implicit baseline
    # or have "standard" category that serves this role
    if not has_baseline:
        # Check if any request name suggests baseline behavior
        baseline_names = {"baseline", "quick", "discovery", "connectivity", "standard"}
        has_baseline = any(any(kw in r.name.lower() for kw in baseline_names) for r in requests)

    assert has_baseline, (
        f"{protocol_name}: no baseline request found. "
        f"Categories present: {sorted({r.category for r in requests})}. "
        f"Every fuzzer should have at least one 'baseline' or "
        f"'quick_coverage' request for connectivity testing."
    )


@pytest.mark.parametrize(
    "protocol_name",
    sorted(AUTH_EXPECTED),
    ids=sorted(AUTH_EXPECTED),
)
def test_auth_category_for_auth_protocols(protocol_name):
    """Protocols with authentication should have an auth-related category."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        pytest.skip(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    auth_cats = {"auth", "security", "no_auth", "preauth"}
    actual_cats = {r.category for r in requests}

    has_auth = bool(auth_cats & actual_cats)
    assert has_auth, (
        f"{protocol_name}: expected auth-related category "
        f"(one of {sorted(auth_cats)}) but found only: {sorted(actual_cats)}"
    )


@pytest.mark.parametrize(
    "protocol_name",
    sorted(OVERFLOW_EXPECTED),
    ids=sorted(OVERFLOW_EXPECTED),
)
def test_overflow_or_boundary_category(protocol_name):
    """Protocols with numeric fields should have overflow or boundary testing."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        pytest.skip(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    overflow_cats = {
        "overflow",
        "boundary",
        "high_crash",
        "cve",
        "dos",
        "edge_cases",
        "attacks",
        "crash",
        "exploit",
    }
    actual_cats = {r.category for r in requests}

    has_overflow = bool(overflow_cats & actual_cats)
    # Also check request names for overflow/boundary patterns
    if not has_overflow:
        overflow_names = {"overflow", "boundary", "extreme", "max", "crash", "length"}
        has_overflow = any(any(kw in r.name.lower() for kw in overflow_names) for r in requests)

    assert has_overflow, (
        f"{protocol_name}: no overflow/boundary testing found. "
        f"Categories present: {sorted(actual_cats)}. "
        f"Protocols with numeric fields need at least one overflow "
        f"or boundary request."
    )


# --------------------------------------------------------------------------- #
# Transport & network-layer balance tests (audit 2026-02-14)
# --------------------------------------------------------------------------- #

# Required categories for transport/network protocols
TRANSPORT_REQUIRED_CATEGORIES = {
    "tcp": {"handshake", "cve", "options"},
    "ipv4": {"baseline", "exploit", "boundary"},
    "ipv6": {"standard", "extension", "cve"},
    "icmp": {"baseline", "high_crash", "comprehensive"},
    "icmpv6": {"baseline", "overflow", "cve", "ndp"},
    "ethernet": {"baseline", "overflow", "injection"},
}

# Transport protocols with overflow/boundary expected
TRANSPORT_OVERFLOW_EXPECTED = {"tcp", "ipv4", "ipv6", "icmp", "icmpv6", "ethernet"}


@pytest.mark.parametrize(
    "protocol_name,required_cats",
    sorted(TRANSPORT_REQUIRED_CATEGORIES.items()),
    ids=sorted(TRANSPORT_REQUIRED_CATEGORIES.keys()),
)
def test_transport_required_categories_present(protocol_name, required_cats):
    """Transport/network fuzzers cover all required categories."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        pytest.skip(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    actual_cats = {r.category for r in requests}

    missing = required_cats - actual_cats
    assert not missing, (
        f"{protocol_name}: missing required categories: {missing}. "
        f"Found categories: {sorted(actual_cats)}. "
        f"Requests: {[(r.name, r.category) for r in requests]}"
    )


@pytest.mark.parametrize(
    "protocol_name",
    sorted(TRANSPORT_REQUIRED_CATEGORIES.keys()),
    ids=sorted(TRANSPORT_REQUIRED_CATEGORIES.keys()),
)
def test_transport_category_diversity(protocol_name):
    """Transport fuzzers with 10+ requests should have at least 3 categories."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        pytest.skip(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    if len(requests) < 10:
        pytest.skip(f"{protocol_name} has {len(requests)} requests, <10")

    actual_cats = {r.category for r in requests}
    assert len(actual_cats) >= 3, (
        f"{protocol_name}: only {len(actual_cats)} categories "
        f"({sorted(actual_cats)}) across {len(requests)} requests. "
        f"Expected at least 3 for transport/network protocols with 10+ requests."
    )


@pytest.mark.parametrize(
    "protocol_name",
    sorted(TRANSPORT_OVERFLOW_EXPECTED),
    ids=sorted(TRANSPORT_OVERFLOW_EXPECTED),
)
def test_transport_has_overflow_or_boundary(protocol_name):
    """Transport protocols should have overflow/boundary/cve testing."""
    fuzzer_class = PROTOCOL_FUZZERS.get(protocol_name)
    if fuzzer_class is None:
        pytest.skip(f"{protocol_name} not available in PROTOCOL_FUZZERS")

    requests = fuzzer_class.get_request_definitions()
    overflow_cats = {
        "overflow",
        "boundary",
        "high_crash",
        "cve",
        "exploit",
        "injection",
        "attack",
    }
    actual_cats = {r.category for r in requests}

    has_overflow = bool(overflow_cats & actual_cats)
    assert has_overflow, (
        f"{protocol_name}: no overflow/boundary/cve testing found. "
        f"Categories: {sorted(actual_cats)}"
    )
